// Generated by `pnpm nrb i18n catalogs`. Do not edit by hand.
import enCommonErrorsCatalog from '@app/i18n-en-common/errors.json';
import enCommonSharedCatalog from '@app/i18n-en-common/shared.json';
import enLandingAppCatalog from '@app/i18n-en-landing/app.json';
import ruCommonErrorsCatalog from '@app/i18n-ru-common/errors.json';
import ruCommonSharedCatalog from '@app/i18n-ru-common/shared.json';
import ruLandingAppCatalog from '@app/i18n-ru-landing/app.json';
import type { Locale, RuntimeLocaleCatalogFileEntry } from '@app/common-i18n-runtime';

export const catalogFileNames = [
  'common/errors.json',
  'common/shared.json',
  'landing/app.json',
] as const;

export const localeCatalogFiles = {
  en: [
    ['common/errors.json', enCommonErrorsCatalog],
    ['common/shared.json', enCommonSharedCatalog],
    ['landing/app.json', enLandingAppCatalog],
  ],
  ru: [
    ['common/errors.json', ruCommonErrorsCatalog],
    ['common/shared.json', ruCommonSharedCatalog],
    ['landing/app.json', ruLandingAppCatalog],
  ],
} as const satisfies Record<Locale, readonly RuntimeLocaleCatalogFileEntry[]>;
