// @requirements REQ-SCAFFOLD-QUALITY-006
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { describe, it } from "node:test";
import { openApiContracts } from "../api/contracts-manifest.ts";
import { isMigrationFilePath } from "../db/migration-naming.ts";
import { collectFiles, workspaceRoot } from "./runtime-utils.ts";
import {
  highEntropySecretPattern,
  isAllowedSecretScanValue,
  isGeneratedArtifact,
  isProductAllowedSecretScanValue,
  isSecretScanIgnoredPath,
  loadProductSecretScanAllowlist,
  parseProductSecretScanAllowlist,
  productSecretScanAllowlistPath,
  secretEntropyThreshold,
  secretValueEntropy,
} from "./secret-scan-policy.ts";

// Header lines the repository's generators actually write, so the exemptions below are keyed on the
// same self-declaration a reader of the artifact sees.
const generatedToastRulesHeader = '{\n  "version": 1,\n  "generatedBy": "@repo/tooling api toast-config generate",\n';
const generatedClientHeader = "/**\n * This file was auto-generated by openapi-typescript.\n */\n";

describe("native secret scan policy", () => {
  it("allows runtime-composed values without allowing static credentials", () => {
    assert.equal(isAllowedSecretScanValue("${encodeURIComponent(password)}@127.0.0.1"), true);
    assert.equal(isAllowedSecretScanValue("actual-static-credential@127.0.0.1"), false);
  });

  it("allows generated HTTP toast variants without allowing the same value in a hand-written file", () => {
    const variant = ["DELETE", "409", "last-auth-method-unlink-forbidden"].join("_");

    assert.equal(
      isAllowedSecretScanValue(
        variant,
        "apps/backend/auth/auth-app-api/contracts/toast/auth-app-api.toast-rules.generated.json",
        generatedToastRulesHeader,
      ),
      true,
    );
    assert.equal(
      isAllowedSecretScanValue(
        variant,
        "libs/frontend/api-client/lib/src/generated/toast/auth-app-api.toast-rules.frontend.generated.json",
        generatedToastRulesHeader,
      ),
      true,
    );
    assert.equal(isAllowedSecretScanValue(variant, "src/runtime-config.json", "{}"), false);
  });

  it("does not let a hand-written file claim the exemption by filename alone", () => {
    const variant = ["DELETE", "409", "last-auth-method-unlink-forbidden"].join("_");

    assert.equal(isAllowedSecretScanValue(variant, "auth-app-api.toast-rules.generated.json", "{}"), false);
  });

  it("allows generated operation ids in every artifact the API generators declare", () => {
    const operationId = ["AgriTechAdminController", "reviewMarketplaceRequestPublication"].join("_");
    assert.ok(secretValueEntropy(operationId) > secretEntropyThreshold);

    for (const contract of openApiContracts()) {
      for (const path of [contract.artifactPath, contract.typesPath, contract.clientOutputPath]) {
        assert.equal(isAllowedSecretScanValue(operationId, path, generatedClientHeader), true, path);
      }
    }
    assert.equal(isAllowedSecretScanValue(operationId, "libs/frontend/lib/src/runtime-config.ts", ""), false);
  });

  it("does not allow credential-shaped values in generated artifacts", () => {
    const generatedPath = "apps/backend/auth/auth-app-api/contracts/toast/auth-app-api.toast-rules.generated.json";

    assert.equal(
      isAllowedSecretScanValue(
        ["ghp", "0123456789abcdefghijklmnopqrstuvwxyz", "ABCD"].join("_"),
        generatedPath,
        generatedToastRulesHeader,
      ),
      false,
    );
    assert.equal(
      isAllowedSecretScanValue(["AgriTechAdminController", "review+Marketplace/Request="].join("_"), generatedPath, generatedToastRulesHeader),
      false,
    );
    assert.equal(
      isAllowedSecretScanValue(["QUFBQUFBQUFBQUJCQkJCQkJDQ0ND", "REREREREREVFRUVF"].join(""), generatedPath, generatedToastRulesHeader),
      false,
    );
  });

  it("allows the migration class names the migration standards gate mandates", () => {
    const className = "Migration20260525184500NormalizeAuthUserDatabaseStandards";
    assert.ok(secretValueEntropy(className) > secretEntropyThreshold);

    assert.equal(isAllowedSecretScanValue(className, "packages/tooling/src/setup/catalog.ts"), true);
    assert.equal(
      isAllowedSecretScanValue(["Migration2026", "aB3dE5gH7jK9lM1nO3pQ5rS7tU9vW1xY3zA5"].join(""), "packages/tooling/src/setup/catalog.ts"),
      false,
    );
  });

  it("calculates entropy for the native high-entropy rule", () => {
    assert.equal(secretValueEntropy("aaaaaaaa"), 0);
    assert.ok(secretValueEntropy("abcdefghijklmnopqrstuvwxyz0123456789") > secretEntropyThreshold);
  });

  it("ignores local Claude worktrees without excluding repository Claude configuration", () => {
    assert.equal(isSecretScanIgnoredPath(".claude/worktrees/feature/src/config.ts"), true);
    assert.equal(isSecretScanIgnoredPath(".claude/settings.json"), false);
  });
});

/**
 * The gate fails builds on files nobody may hand-edit, so the exemptions are pinned against the
 * real tree rather than against handwritten samples: the next artifact family a generator emits, or
 * the next migration whose description happens to use a few more distinct letters, has to keep the
 * scan green here before it can turn a product's pipeline red.
 */
describe("native secret scan policy over the repository", () => {
  it("reports nothing in the artifacts the API generators emit", () => {
    const roots = new Set(
      openApiContracts().flatMap((contract) => [
        dirname(dirname(join(workspaceRoot, contract.artifactPath))),
        dirname(join(workspaceRoot, contract.typesPath)),
        dirname(join(workspaceRoot, contract.clientOutputPath)),
      ]),
    );
    const findings: string[] = [];
    let generatedFiles = 0;

    for (const root of roots) {
      for (const file of collectFiles(root)) {
        const relativePath = file.slice(workspaceRoot.length + 1).replaceAll("\\", "/");
        const text = readFileSync(file, "utf8");
        if (!isGeneratedArtifact(relativePath, text)) continue;
        generatedFiles += 1;
        for (const match of text.matchAll(highEntropySecretPattern)) {
          const value = match[1] ?? "";
          if (isAllowedSecretScanValue(value, relativePath, text) || secretValueEntropy(value) < secretEntropyThreshold) continue;
          findings.push(`${relativePath}: ${value}`);
        }
      }
    }

    assert.ok(generatedFiles >= openApiContracts().length, `expected generated artifacts under ${[...roots].join(", ")}`);
    assert.deepEqual(findings, []);
  });

  it("reports no migration name the migration standards gate mandates", () => {
    const migrations = collectFiles(join(workspaceRoot, "libs"), { include: (path) => isMigrationFilePath(path) });

    assert.ok(migrations.length > 0);
    for (const file of migrations) {
      const className = basename(file, ".ts");
      assert.equal(isAllowedSecretScanValue(className, file), true, className);
    }
  });
});

/**
 * The product-owned seam. The base policy above stays closed so a boilerplate upgrade never
 * conflicts with a product's fixtures, exactly as the RBAC catalog composes product extensions over
 * a closed base.
 */
describe("product secret scan allowlist", () => {
  const registration = { id: "marketplace-fixtures", path: "^libs/backend/marketplace/.*\\.spec\\.ts$", values: ["^ik[0-9a-f]{40}$"] };
  const registered = `ik${"0123456789abcdef".repeat(2)}01234567`;

  it("allows a registered value only under the path that registered it", () => {
    const entries = parseProductSecretScanAllowlist({ entries: [registration] }, productSecretScanAllowlistPath);

    assert.equal(isProductAllowedSecretScanValue(entries, registered, "libs/backend/marketplace/lib/src/orders.spec.ts"), true);
    assert.equal(isProductAllowedSecretScanValue(entries, registered, "libs/backend/marketplace/lib/src/orders.ts"), false);
    assert.equal(isProductAllowedSecretScanValue(entries, `${registered}00`, "libs/backend/marketplace/lib/src/orders.spec.ts"), false);
  });

  it("rejects a registration that would widen the gate instead of narrowing it", () => {
    const rejected: Record<string, unknown> = {
      "unanchored path": { entries: [{ id: "a", path: "marketplace", values: ["^ik[0-9a-f]{40}$"] }] },
      "path without a literal prefix": { entries: [{ id: "a", path: "^.*$", values: ["^ik[0-9a-f]{40}$"] }] },
      "no values": { entries: [{ id: "a", path: "^libs/backend/marketplace/.*$", values: [] }] },
      "unanchored value": { entries: [{ id: "a", path: "^libs/backend/marketplace/.*$", values: ["ik"] }] },
      "value matching anything": { entries: [{ id: "a", path: "^libs/backend/marketplace/.*$", values: ["^.+$"] }] },
      "unparsable value": { entries: [{ id: "a", path: "^libs/backend/marketplace/.*$", values: ["^ik[0-9a-f$"] }] },
      "missing id": { entries: [{ path: "^libs/backend/marketplace/.*$", values: ["^ik[0-9a-f]{40}$"] }] },
      "unknown key": { entries: [], allowAll: true },
      "entries of the wrong shape": { entries: {} },
    };

    for (const [reason, document] of Object.entries(rejected)) {
      assert.throws(
        () => parseProductSecretScanAllowlist(document, productSecretScanAllowlistPath),
        new RegExp(productSecretScanAllowlistPath.replaceAll(".", "\\.")),
        reason,
      );
    }
  });

  it("registers all entries or none, so one bad entry cannot leave a half-applied policy", () => {
    const document = { entries: [registration, { id: "broken", path: "^.*$", values: ["^.+$"] }] };

    assert.throws(() => parseProductSecretScanAllowlist(document, productSecretScanAllowlistPath));
    assert.equal(isProductAllowedSecretScanValue(loadProductSecretScanAllowlist(), registered, "libs/backend/marketplace/lib/src/orders.spec.ts"), false);
  });

  it("reads an absent file as no registrations and ships none of its own", () => {
    assert.deepEqual(loadProductSecretScanAllowlist(join(workspaceRoot, "config/secret-scan.allowlist.absent.json")), []);
    assert.deepEqual(loadProductSecretScanAllowlist(), []);
  });
});
