import { existsSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";
import { openApiContracts } from "../api/contracts-manifest.ts";
import { migrationClassNamePattern } from "../db/migration-naming.ts";
import { workspaceRoot } from "./runtime-utils.ts";

/** Quoted runs long enough to be worth measuring; the alphabet is base64 plus the URL-safe variants. */
export const highEntropySecretPattern = /["']([A-Za-z0-9+/=_-]{40,})["']/g;

/**
 * Shannon entropy above which such a run is reported. Named because a heuristic that fails a build
 * has to be legible to whoever it fails on: the generated and mandated identifiers exempted below
 * clear it by hundredths of a bit, so the exemptions carry the whole margin.
 */
export const secretEntropyThreshold = 4.4;

/**
 * Every generator in this repository stamps its output with a "generated by" line — `pnpm nrb
 * setup`, `pnpm api:clients`, `api toast-config generate`, openapi-typescript. Recognising the
 * marker rather than a list of filenames means an artifact family added later is covered the day
 * its generator writes it, and a file that is merely named like generated output cannot claim the
 * exemption. Only the header is read, because that is where every generator writes the marker.
 */
const generatedMarkerPattern = /generated\s*by/iu;
const generatedMarkerHeaderLength = 512;

/**
 * OpenAPI documents are the exception: they are verbatim tool output with nowhere to put a comment,
 * so they are recognised by the manifest that tells the generators where to write them. The set is
 * resolved once because the scan asks this question for every candidate value in the tree.
 */
let generatedContractPathCache: Set<string> | undefined;
function generatedContractPaths() {
  generatedContractPathCache ??= new Set(
    openApiContracts().flatMap((contract) => [contract.artifactPath, contract.typesPath, contract.clientOutputPath]),
  );
  return generatedContractPathCache;
}

/**
 * The two value shapes those artifacts legitimately carry: the `<Controller>_<handler>` operation
 * ids Nest derives (see `operationPascalCase` in the api generator), which the OpenAPI documents,
 * the derived client modules and the toast rules all repeat, and the HTTP toast variants. Both are
 * kept literal rather than generalised to "looks like an identifier": a base64 payload drawn from
 * the alphabet minus `+/=` is letters and digits too, and routinely contains a camel-case break.
 */
const nestOperationIdPattern = /^[A-Z][A-Za-z0-9]*Controller_[a-z][A-Za-z0-9]*$/u;
const generatedToastVariantPattern =
  /^(?:GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS)_(?:[1-5]\d{2}|ERR|NET)(?:_[a-z][a-z0-9]*(?:-[a-z0-9]+)*)?$/u;

/** The one file a product edits to register its own key-shaped fixtures. */
export const productSecretScanAllowlistPath = "config/secret-scan.allowlist.json";

export interface ProductSecretScanAllowlistEntry {
  readonly id: string;
  readonly path: RegExp;
  readonly values: readonly RegExp[];
}

const anchoredRegexPattern = /^\^[\s\S]*\$$/u;
const literalPathPrefixPattern = /^\^[A-Za-z0-9_-]{3,}/u;
/**
 * A value pattern that matches this — an arbitrary string no fixture would ever register — is
 * matching everything, which is how an allowlist entry turns into a disabled gate.
 */
const overBroadProbe = "zq7Xk2p9WvTb4Lm1Rc8Ns5Yd3Hg6Jf0Ae2Uo9Iv";

export function secretValueEntropy(value: string) {
  const counts = new Map<string, number>();
  for (const char of value) counts.set(char, (counts.get(char) ?? 0) + 1);
  return [...counts.values()].reduce((sum, count) => {
    const probability = count / value.length;
    return sum - probability * Math.log2(probability);
  }, 0);
}

export function isGeneratedArtifact(relativePath: string, fileText = "") {
  return generatedMarkerPattern.test(fileText.slice(0, generatedMarkerHeaderLength)) || generatedContractPaths().has(relativePath);
}

function isGeneratedArtifactValue(value: string) {
  return nestOperationIdPattern.test(value) || generatedToastVariantPattern.test(value);
}

function compileAllowlistPattern(source: string, label: string, pattern: unknown, kind: "path" | "value") {
  if (typeof pattern !== "string" || pattern === "") throw new Error(`${source}: ${label} declares a ${kind} that is not a non-empty string`);
  if (!anchoredRegexPattern.test(pattern)) throw new Error(`${source}: ${label} declares an unanchored ${kind} "${pattern}"; anchor it with ^ and $`);
  if (kind === "path" && !literalPathPrefixPattern.test(pattern)) {
    throw new Error(`${source}: ${label} declares the over-broad path "${pattern}"; start it with at least three literal characters`);
  }
  let compiled: RegExp;
  try {
    compiled = new RegExp(pattern, "u");
  } catch (error) {
    throw new Error(`${source}: ${label} declares the unparsable ${kind} "${pattern}" (${(error as Error).message})`);
  }
  if (kind === "value" && (compiled.test(overBroadProbe) || compiled.test(""))) {
    throw new Error(`${source}: ${label} declares the over-broad value "${pattern}"; it matches unrelated strings`);
  }
  return compiled;
}

/**
 * Validates a product registration as a whole and throws on the first problem, so a malformed file
 * fails the scan loudly instead of half-registering — or, worse, silently allowing everything.
 */
export function parseProductSecretScanAllowlist(document: unknown, source: string): readonly ProductSecretScanAllowlistEntry[] {
  if (typeof document !== "object" || document === null || Array.isArray(document)) throw new Error(`${source}: must contain a JSON object`);
  const record = document as Record<string, unknown>;
  for (const key of Object.keys(record)) {
    if (key !== "entries" && key !== "documentation") throw new Error(`${source}: declares the unknown key "${key}"`);
  }
  const entries = record.entries ?? [];
  if (!Array.isArray(entries)) throw new Error(`${source}: "entries" must be an array`);

  return entries.map((entry, index) => {
    const label = `entry ${index}`;
    if (typeof entry !== "object" || entry === null || Array.isArray(entry)) throw new Error(`${source}: ${label} must be an object`);
    const fields = entry as Record<string, unknown>;
    for (const key of Object.keys(fields)) {
      if (key !== "id" && key !== "path" && key !== "values") throw new Error(`${source}: ${label} declares the unknown key "${key}"`);
    }
    const id = fields.id;
    if (typeof id !== "string" || id === "") throw new Error(`${source}: ${label} is missing a non-empty "id"`);
    const named = `entry "${id}"`;
    const values = fields.values;
    if (!Array.isArray(values) || values.length === 0) throw new Error(`${source}: ${named} registers no values`);

    return {
      id,
      path: compileAllowlistPattern(source, named, fields.path, "path"),
      values: values.map((value) => compileAllowlistPattern(source, named, value, "value")),
    };
  });
}

export function loadProductSecretScanAllowlist(filePath = join(workspaceRoot, productSecretScanAllowlistPath)) {
  if (!existsSync(filePath)) return [];
  const source = relative(workspaceRoot, filePath).replaceAll("\\", "/") || filePath;
  let document: unknown;
  try {
    document = JSON.parse(readFileSync(filePath, "utf8"));
  } catch (error) {
    throw new Error(`${source}: is not valid JSON (${(error as Error).message})`);
  }
  return parseProductSecretScanAllowlist(document, source);
}

export function isProductAllowedSecretScanValue(
  entries: readonly ProductSecretScanAllowlistEntry[],
  value: string,
  relativePath: string,
) {
  return entries.some((entry) => entry.path.test(relativePath) && entry.values.some((pattern) => pattern.test(value)));
}

let productAllowlistCache: readonly ProductSecretScanAllowlistEntry[] | undefined;
function productAllowlist() {
  productAllowlistCache ??= loadProductSecretScanAllowlist();
  return productAllowlistCache;
}

export function isAllowedSecretScanValue(value: string, relativePath = "", fileText = "") {
  if (value.includes("${")) return true;
  if (/example|sample|fixture|test|dummy|changeme|placeholder|process\.env/i.test(value)) return true;
  if (migrationClassNamePattern.test(value)) return true;
  if (relativePath.endsWith("env-loader.ts") && /postgres/i.test(value)) return true;
  if (relativePath === "scripts/validate-deployment-config.mjs" && value.startsWith("SITE_DIST_ROOT=/workspace/")) return true;
  if (isGeneratedArtifact(relativePath, fileText) && isGeneratedArtifactValue(value)) return true;
  return isProductAllowedSecretScanValue(productAllowlist(), value, relativePath);
}

export function isSecretScanIgnoredPath(relativePath: string) {
  return relativePath === ".claude/worktrees" || relativePath.startsWith(".claude/worktrees/");
}
