// Generated by `pnpm nrb setup`. Do not edit by hand.
import { Global, Module } from '@nestjs/common';
import { S3Module } from '@app/backend-common-s3';
import { PostgresMainModule } from '@app/backend-postgres-main';
import { AuthPostgresModule } from '@app/backend-postgres-main-auth';
import { FeatureFlagsPostgresModule } from '@app/backend-postgres-main-feature-flags';
import { NotificationPostgresModule } from '@app/backend-postgres-main-notification';

@Global()
@Module({ imports: [AuthPostgresModule, FeatureFlagsPostgresModule, NotificationPostgresModule, PostgresMainModule.forRoot(), S3Module.forRoot()], exports: [AuthPostgresModule, FeatureFlagsPostgresModule, NotificationPostgresModule, PostgresMainModule, S3Module] })
export class AdminAppApiCapabilitiesModule {}
