import { MikroOrmModule } from '@mikro-orm/nestjs';
import { Module } from '@nestjs/common';
import { AuthTokenCleanupService } from './auth-token-cleanup.service';
import {
  AdminAuditLogEntitySchema,
  AuthLinkTokenEntitySchema,
  AuthMethodEntitySchema,
  AuthPermissionEntitySchema,
  AuthProviderTokenEntitySchema,
  AuthRefreshTokenEntitySchema,
  AuthRoleEntitySchema,
  AuthRolePermissionEntitySchema,
  AuthTenantEntitySchema,
  AuthTenantInvitationEntitySchema,
  AuthTenantMembershipEntitySchema,
  AuthUserEntitySchema,
  AuthUserRoleEntitySchema,
  AuthUserTokenEntitySchema,
  ExternalIdentityEntitySchema,
  TransactionalOutboxEventEntitySchema,
} from './infrastructure/data-access/entities';
import {
  AdminAuditLogRepository,
  AdminUserMutationRepository,
  AuthLinkTokenRepository,
  AuthMethodRepository,
  AuthProviderTokenRepository,
  AuthRoleRepository,
  AuthTokenRepository,
  AuthUserRepository,
  AuthUserRoleRepository,
  ExternalIdentityRepository,
} from './infrastructure/data-access/repositories';

@Module({
  imports: [
    MikroOrmModule.forFeature([
      AuthUserEntitySchema,
      AuthTenantEntitySchema,
      AuthTenantMembershipEntitySchema,
      AuthTenantInvitationEntitySchema,
      AuthRefreshTokenEntitySchema,
      AuthUserTokenEntitySchema,
      ExternalIdentityEntitySchema,
      AuthMethodEntitySchema,
      AuthLinkTokenEntitySchema,
      AuthProviderTokenEntitySchema,
      AdminAuditLogEntitySchema,
      TransactionalOutboxEventEntitySchema,
      AuthRoleEntitySchema,
      AuthPermissionEntitySchema,
      AuthRolePermissionEntitySchema,
      AuthUserRoleEntitySchema,
    ]),
  ],
  providers: [
    AuthUserRepository,
    AuthTokenRepository,
    AuthTokenCleanupService,
    ExternalIdentityRepository,
    AuthMethodRepository,
    AuthLinkTokenRepository,
    AuthProviderTokenRepository,
    AdminAuditLogRepository,
    AdminUserMutationRepository,
    AuthRoleRepository,
    AuthUserRoleRepository,
  ],
  exports: [
    MikroOrmModule,
    AuthUserRepository,
    AuthTokenRepository,
    AuthTokenCleanupService,
    ExternalIdentityRepository,
    AuthMethodRepository,
    AuthLinkTokenRepository,
    AuthProviderTokenRepository,
    AdminAuditLogRepository,
    AdminUserMutationRepository,
    AuthRoleRepository,
    AuthUserRoleRepository,
  ],
})
export class AuthPostgresModule {}
