packages:
  - "apps/frontend/*"
  - "apps/backend/*"
  - "libs/frontend/*/lib"
  - "libs/common/*/lib"
  - "libs/backend/common/*/lib"
  - "libs/feature/*/*/lib"
  - "libs/backend/feature/*/*/lib"
  - "libs/backend/postgres/*/*/lib"
  - "packages/tooling"

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild
  - nx

ignoredBuiltDependencies:
  - "@scarf/scarf"
  - less
  - unrs-resolver
