packages:
  - "apps/frontend/*"
  - "apps/backend/*"
  - "libs/frontend/*"
  - "libs/common/*"
  - "libs/features/*/*"
  - "libs/postgres/*/*"
  - "libs/backend"

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild
  - nx

ignoredBuiltDependencies:
  - "@scarf/scarf"
  - less
  - unrs-resolver

allowBuilds:
  "@nestjs/core": set this to true or false
  "@parcel/watcher": set this to true or false
  "@scarf/scarf": set this to true or false
  "@swc/core": set this to true or false
  esbuild: set this to true or false
  less: set this to true or false
  nx: set this to true or false
  unrs-resolver: set this to true or false
