// Generated by `pnpm nrb i18n catalogs`. Do not edit by hand.
import enCommonErrorsCatalog from '@app/i18n-en-common/errors.json';
import enCommonSharedCatalog from '@app/i18n-en-common/shared.json';
import ruCommonErrorsCatalog from '@app/i18n-ru-common/errors.json';
import ruCommonSharedCatalog from '@app/i18n-ru-common/shared.json';
import zhCommonErrorsCatalog from '@app/i18n-zh-common/errors.json';
import zhCommonSharedCatalog from '@app/i18n-zh-common/shared.json';
import type { Locale, RuntimeLocaleCatalogFileEntry } from '@app/common-i18n-runtime';

export const catalogFileNames = [
  'common/errors.json',
  'common/shared.json',
] as const;

export const localeCatalogFiles = {
  en: [
    ['common/errors.json', enCommonErrorsCatalog],
    ['common/shared.json', enCommonSharedCatalog],
  ],
  ru: [
    ['common/errors.json', ruCommonErrorsCatalog],
    ['common/shared.json', ruCommonSharedCatalog],
  ],
  zh: [
    ['common/errors.json', zhCommonErrorsCatalog],
    ['common/shared.json', zhCommonSharedCatalog],
  ],
} as const satisfies Record<Locale, readonly RuntimeLocaleCatalogFileEntry[]>;
