import { getProblemTypeDefinition, problemTypeForCode, type ProblemTypeCode } from '@app/common-problem-details';
import type { OpenApiSchemaObject } from '../type/open-api-schema.type';
import { mapHttpStatusToProblemTitle } from './map-http-status-to-problem-title.util';

const standardProblemProperties: Record<string, OpenApiSchemaObject> = {
  type: {
    type: 'string',
    format: 'uri-reference',
    example: 'about:blank',
    description: 'A URI reference identifying the problem type; defaults to about:blank when omitted.',
  },
  title: {
    type: 'string',
    description: 'A short human-readable summary of the problem type.',
  },
  status: {
    type: 'integer',
    minimum: 100,
    maximum: 599,
    description: 'The HTTP status code generated by the origin server for this occurrence.',
  },
  detail: {
    type: 'string',
    description: 'A human-readable explanation specific to this occurrence.',
  },
  instance: {
    type: 'string',
    format: 'uri-reference',
    description: 'A URI reference identifying this specific occurrence.',
  },
};

/** RFC 9457's open base object. Standard members are optional and extensions are allowed. */
export const problemDetailsOpenApiSchema: OpenApiSchemaObject = {
  type: 'object',
  properties: standardProblemProperties,
  additionalProperties: true,
};

/** The stricter profile emitted by this repository for a generic HTTP status. */
export function getProblemDetailsSchema(status: number): OpenApiSchemaObject {
  const title = mapHttpStatusToProblemTitle(status);

  return {
    type: 'object',
    required: ['type', 'title', 'status'],
    properties: {
      ...standardProblemProperties,
      type: {
        ...standardProblemProperties.type,
        enum: ['about:blank'],
        example: 'about:blank',
      },
      title: {
        ...standardProblemProperties.title,
        example: title,
      },
      status: {
        ...standardProblemProperties.status,
        enum: [status],
        example: status,
      },
    },
    additionalProperties: true,
  };
}

/** The exact response profile for a registered problem type. */
export function getRegisteredProblemDetailsSchema(code: ProblemTypeCode): OpenApiSchemaObject {
  const definition = getProblemTypeDefinition(code);
  if (!definition) {
    throw new TypeError(`Unknown registered problem type: ${JSON.stringify(code)}`);
  }

  const extensionProperties = Object.fromEntries(
    definition.extensions
      .filter(({ name }) => name !== 'code')
      .map(({ description, name }) => [name, { description } satisfies OpenApiSchemaObject]),
  );

  return {
    type: 'object',
    required: ['type', 'title', 'status', 'detail', 'code'],
    properties: {
      ...standardProblemProperties,
      type: {
        ...standardProblemProperties.type,
        enum: [problemTypeForCode(code)],
        example: problemTypeForCode(code),
      },
      title: {
        ...standardProblemProperties.title,
        example: definition.title,
        description: 'A short human-readable summary of the problem type, localized according to content negotiation.',
      },
      status: {
        ...standardProblemProperties.status,
        enum: [definition.status],
        example: definition.status,
      },
      detail: {
        ...standardProblemProperties.detail,
        example: definition.detail,
      },
      code: {
        type: 'string',
        enum: [code],
        example: code,
        description: 'Stable short alias for the problem type URI.',
      },
      ...extensionProperties,
    },
    additionalProperties: true,
  };
}
