import type { OpenApiSchemaObject } from '../type/open-api-schema.type';
import { mapHttpStatusToProblemTitle } from './map-http-status-to-problem-title.util';

const standardProblemProperties: Record<string, OpenApiSchemaObject> = {
  type: {
    type: 'string',
    format: 'uri-reference',
    example: 'about:blank',
    description: 'A URI reference identifying the problem type; defaults to about:blank when omitted.',
  },
  title: {
    type: 'string',
    description: 'A short human-readable summary of the problem type.',
  },
  status: {
    type: 'integer',
    minimum: 100,
    maximum: 599,
    description: 'The HTTP status code generated by the origin server for this occurrence.',
  },
  detail: {
    type: 'string',
    description: 'A human-readable explanation specific to this occurrence.',
  },
  instance: {
    type: 'string',
    format: 'uri-reference',
    description: 'A URI reference identifying this specific occurrence.',
  },
};

/** RFC 9457's open base object. Standard members are optional and extensions are allowed. */
export const problemDetailsOpenApiSchema: OpenApiSchemaObject = {
  type: 'object',
  properties: standardProblemProperties,
  additionalProperties: true,
};

/** The stricter profile emitted by this repository for a generic HTTP status. */
export function getProblemDetailsSchema(status: number): OpenApiSchemaObject {
  const title = mapHttpStatusToProblemTitle(status);

  return {
    type: 'object',
    required: ['type', 'title', 'status'],
    properties: {
      ...standardProblemProperties,
      type: {
        ...standardProblemProperties.type,
        enum: ['about:blank'],
        example: 'about:blank',
      },
      title: {
        ...standardProblemProperties.title,
        example: title,
      },
      status: {
        ...standardProblemProperties.status,
        enum: [status],
        example: status,
      },
    },
    additionalProperties: true,
  };
}
