import { HttpStatus } from '@nestjs/common';
import { ProblemTypeBaseUrl } from '../const/problem-type-base-url.const';
import type { OpenApiSchemaObject } from '../type/open-api-schema.type';
import { mapHttpStatusToProblemTitle } from './map-http-status-to-problem-title.util';
import { problemCodeForStatus } from './problem-code-for-status.util';

// RFC 9457 Compliant Problem Details OpenAPI Schema
export const problemDetailsOpenApiSchema: OpenApiSchemaObject = {
  type: 'object',
  required: ['type', 'title', 'status', 'code'],
  properties: {
    type: { type: 'string', example: 'about:blank' },
    title: { type: 'string', example: 'Bad Request' },
    status: { type: 'integer', example: 400 },
    detail: { type: 'string' },
    instance: { type: 'string' },
    code: { type: 'string' },
    localizedDetail: {
      type: 'string',
      description:
        'A localized human-display explanation for this occurrence. Display-only extension; do not use for program logic.',
    },
    errors: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          property: { type: 'string' },
          message: { type: 'string' },
          detail: { type: 'string' },
          pointer: { type: 'string', example: '/profile/email' },
          constraints: {
            type: 'object',
            additionalProperties: { type: 'string' },
          },
        },
        required: ['property', 'constraints'],
      },
    },
  },
};

export function getProblemDetailsSchema(status: number): OpenApiSchemaObject {
  const title = mapHttpStatusToProblemTitle(status);
  const code = problemCodeForStatus(status);
  const isBadRequest = status === Number(HttpStatus.BAD_REQUEST);

  const properties: Record<string, OpenApiSchemaObject> = {
    type: {
      type: 'string',
      example: `${ProblemTypeBaseUrl}:${code}`,
      description: 'A URI reference that identifies the problem type.',
    },
    title: {
      type: 'string',
      example: title,
      description: 'A short, human-readable summary of the problem type.',
    },
    status: {
      type: 'integer',
      example: status,
      description: 'The HTTP status code generated by the origin server.',
    },
    detail: {
      type: 'string',
      description: 'A human-readable explanation specific to this occurrence.',
    },
    instance: {
      type: 'string',
      description:
        'A URI reference that identifies the specific occurrence of the problem. Omitted unless a real occurrence URI/reference is available.',
    },
    localizedDetail: {
      type: 'string',
      description:
        'A localized human-display explanation for this occurrence. Display-only extension; do not use for program logic.',
    },
    code: {
      type: 'string',
      example: code,
      description: 'A stable machine-readable error code for programmatic handling.',
    },
  };

  if (isBadRequest) {
    properties.errors = {
      type: 'array',
      description: 'An array of validation errors (present for validation failures).',
      items: {
        type: 'object',
        properties: {
          property: {
            type: 'string',
            description: 'The field that failed validation.',
          },
          message: {
            type: 'string',
            description: 'The localized error message.',
          },
          detail: {
            type: 'string',
            description: 'A localized human-readable explanation for this validation issue.',
          },
          pointer: {
            type: 'string',
            description: 'A JSON Pointer identifying the nested request member that failed validation.',
            example: '/profile/email',
          },
          constraints: {
            type: 'object',
            additionalProperties: { type: 'string' },
            description: 'The validation constraints that failed.',
          },
        },
        required: ['property', 'constraints'],
      },
    };
  }

  return {
    type: 'object',
    required: ['type', 'title', 'status', 'code'],
    properties,
  };
}
