#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'
umask 027

CONFIG_ROOT="${NRB_CONFIG_ROOT:-/etc/nest-react-boilerplate}"
SERVER_ENV="${CONFIG_ROOT}/server.env"
PRODUCTION_ENV="${CONFIG_ROOT}/.env.production"

# Unattended one-line install. Only the two values that cannot be generated are
# accepted here (public domain + ACME contact); every password/secret/key that can
# be generated is generated by `serverctl` with OpenSSL.
#
#   curl -fsSL <raw-url>/deploy/single-server/bootstrap.sh \
#     | sudo bash -s -- --domain acme.example --email ops@acme.example --apply
PUBLIC_DOMAIN_INPUT=''
CERTBOT_EMAIL_INPUT=''
IMAGE_REGISTRY_INPUT=''
IMAGE_TAG_INPUT=''
RUNTIME_MODE_INPUT=''
APPLY_AFTER_BOOTSTRAP=false

usage() {
  cat <<'USAGE'
Usage: bootstrap.sh [--domain <dns-name>] [--email <acme-contact>] [--apply]
                    [--runtime compose|native]
                    [--registry <ref>] [--image-tag <sha-...>]
                    [--repository <git-url>] [--branch <name>]

With no options it provisions the host and stops, leaving placeholder config to
edit. With --domain/--email/--apply it performs a complete unattended install.

--runtime selects what the host runs: "compose" (default) deploys the published
container images, "native" installs PostgreSQL, Redis, and PM2-supervised Node
processes with no Docker at all. --registry/--image-tag apply to compose only.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain) PUBLIC_DOMAIN_INPUT="${2:?--domain requires a value}"; shift 2 ;;
    --domain=*) PUBLIC_DOMAIN_INPUT="${1#*=}"; shift ;;
    --email) CERTBOT_EMAIL_INPUT="${2:?--email requires a value}"; shift 2 ;;
    --email=*) CERTBOT_EMAIL_INPUT="${1#*=}"; shift ;;
    --registry) IMAGE_REGISTRY_INPUT="${2:?--registry requires a value}"; shift 2 ;;
    --registry=*) IMAGE_REGISTRY_INPUT="${1#*=}"; shift ;;
    --image-tag) IMAGE_TAG_INPUT="${2:?--image-tag requires a value}"; shift 2 ;;
    --image-tag=*) IMAGE_TAG_INPUT="${1#*=}"; shift ;;
    --repository) REPOSITORY_URL="${2:?--repository requires a value}"; shift 2 ;;
    --repository=*) REPOSITORY_URL="${1#*=}"; shift ;;
    --branch) REPOSITORY_BRANCH="${2:?--branch requires a value}"; shift 2 ;;
    --branch=*) REPOSITORY_BRANCH="${1#*=}"; shift ;;
    --runtime) RUNTIME_MODE_INPUT="${2:?--runtime requires a value}"; shift 2 ;;
    --runtime=*) RUNTIME_MODE_INPUT="${1#*=}"; shift ;;
    --apply) APPLY_AFTER_BOOTSTRAP=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) printf 'unknown argument: %s\n' "$1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ -n "${PUBLIC_DOMAIN_INPUT}" ]]; then
  [[ "${PUBLIC_DOMAIN_INPUT}" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$ ]] || {
    printf -- '--domain must be a bare DNS name such as acme.example\n' >&2
    exit 1
  }
fi
if [[ -n "${CERTBOT_EMAIL_INPUT}" ]]; then
  [[ "${CERTBOT_EMAIL_INPUT}" == *@*.* && "${CERTBOT_EMAIL_INPUT}" != *@example.com ]] || {
    printf -- '--email must be a real reachable address (example.com is rejected by the controller)\n' >&2
    exit 1
  }
fi
if [[ -n "${RUNTIME_MODE_INPUT}" ]]; then
  [[ "${RUNTIME_MODE_INPUT}" == 'compose' || "${RUNTIME_MODE_INPUT}" == 'native' ]] || {
    printf -- '--runtime must be compose or native\n' >&2
    exit 1
  }
  # A native host builds from this checkout and has no images, so accepting an image
  # reference would silently do nothing.
  if [[ "${RUNTIME_MODE_INPUT}" == 'native' && ( -n "${IMAGE_REGISTRY_INPUT}" || -n "${IMAGE_TAG_INPUT}" ) ]]; then
    printf -- '--runtime=native builds from source; --registry/--image-tag do not apply\n' >&2
    exit 1
  fi
fi
if [[ "${APPLY_AFTER_BOOTSTRAP}" == 'true' && ( -z "${PUBLIC_DOMAIN_INPUT}" || -z "${CERTBOT_EMAIL_INPUT}" ) ]]; then
  printf -- '--apply requires both --domain and --email\n' >&2
  exit 1
fi

existing_value() {
  local key="$1"
  [[ -f "${SERVER_ENV}" ]] || return 0
  awk -v key="${key}" '
    $0 ~ "^" key "=" {
      sub("^" key "=", "");
      gsub(/^\047|\047$/, "");
      gsub(/^\042|\042$/, "");
      print;
      exit;
    }
  ' "${SERVER_ENV}"
}

APP_ROOT="${APP_ROOT:-$(existing_value APP_ROOT)}"
APP_ROOT="${APP_ROOT:-/opt/nest-react-boilerplate}"
REPOSITORY_URL="${REPOSITORY_URL:-$(existing_value REPOSITORY_URL)}"
REPOSITORY_URL="${REPOSITORY_URL:-https://github.com/your-github-org/nest-react-boilerplate.git}"
REPOSITORY_BRANCH="${REPOSITORY_BRANCH:-$(existing_value REPOSITORY_BRANCH)}"
REPOSITORY_BRANCH="${REPOSITORY_BRANCH:-main}"

[[ "${EUID}" -eq 0 ]] || { printf 'bootstrap must run as root (use sudo)\n' >&2; exit 1; }
[[ "${CONFIG_ROOT}" =~ ^/[A-Za-z0-9._/-]+$ ]] || { printf 'NRB_CONFIG_ROOT must be an absolute path without spaces\n' >&2; exit 1; }
[[ "${APP_ROOT}" =~ ^/[A-Za-z0-9._/-]+$ ]] || { printf 'APP_ROOT must be an absolute path without spaces\n' >&2; exit 1; }
[[ "${CONFIG_ROOT}" != '/' && "${CONFIG_ROOT}" != '/etc' ]] || { printf 'NRB_CONFIG_ROOT must be a dedicated subdirectory\n' >&2; exit 1; }
[[ "${APP_ROOT}" != '/' && "${APP_ROOT}" != '/opt' && "${APP_ROOT}" != '/srv' ]] || { printf 'APP_ROOT must be a dedicated subdirectory\n' >&2; exit 1; }
[[ "${REPOSITORY_BRANCH}" =~ ^[A-Za-z0-9][A-Za-z0-9._/-]*$ ]] || { printf 'REPOSITORY_BRANCH is invalid\n' >&2; exit 1; }
command -v apt-get >/dev/null 2>&1 || { printf 'bootstrap supports Ubuntu and Debian\n' >&2; exit 1; }

upsert_environment_value() {
  local file="$1" key="$2" value="$3" temporary
  temporary="$(mktemp "${file}.XXXXXX")"
  awk -v key="${key}" -v value="${value}" '
    BEGIN { found = 0 }
    $0 ~ "^" key "=" { print key "=" value; found = 1; next }
    { print }
    END { if (!found) print key "=" value }
  ' "${file}" >"${temporary}"
  chmod --reference="${file}" "${temporary}"
  chown --reference="${file}" "${temporary}"
  mv -f "${temporary}" "${file}"
}

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y --no-install-recommends ca-certificates git openssl

if [[ -d "${APP_ROOT}/.git" ]]; then
  [[ -z "$(git -c safe.directory="${APP_ROOT}" -C "${APP_ROOT}" status --porcelain)" ]] || {
    printf 'existing checkout is dirty; refusing to overwrite %s\n' "${APP_ROOT}" >&2
    exit 1
  }
  git -c safe.directory="${APP_ROOT}" -C "${APP_ROOT}" fetch --prune origin
  git -c safe.directory="${APP_ROOT}" -C "${APP_ROOT}" checkout "${REPOSITORY_BRANCH}"
  git -c safe.directory="${APP_ROOT}" -C "${APP_ROOT}" merge --ff-only "origin/${REPOSITORY_BRANCH}"
elif [[ -e "${APP_ROOT}" && -n "$(find "${APP_ROOT}" -mindepth 1 -maxdepth 1 -print -quit)" ]]; then
  printf 'APP_ROOT exists and is not an empty repository: %s\n' "${APP_ROOT}" >&2
  exit 1
else
  mkdir -p "$(dirname "${APP_ROOT}")"
  git clone --branch "${REPOSITORY_BRANCH}" --single-branch "${REPOSITORY_URL}" "${APP_ROOT}"
fi

server_environment_existed=false
[[ ! -f "${SERVER_ENV}" ]] || server_environment_existed=true
# The runtime has to be known before `init`, which derives the whole production
# environment from it — a native host needs loopback endpoints instead of the
# example's Compose service names.
if [[ -n "${RUNTIME_MODE_INPUT}" ]]; then
  install -d -m 700 "${CONFIG_ROOT}"
  [[ -f "${SERVER_ENV}" ]] || install -m 600 "${APP_ROOT}/deploy/single-server/server.env.example" "${SERVER_ENV}"
  upsert_environment_value "${SERVER_ENV}" RUNTIME_MODE "${RUNTIME_MODE_INPUT}"
fi
NRB_CONFIG_ROOT="${CONFIG_ROOT}" "${APP_ROOT}/deploy/single-server/serverctl" init
if [[ "${server_environment_existed}" == 'false' ]]; then
  upsert_environment_value "${SERVER_ENV}" APP_ROOT "${APP_ROOT}"
  upsert_environment_value "${SERVER_ENV}" REPOSITORY_URL "${REPOSITORY_URL}"
  upsert_environment_value "${SERVER_ENV}" REPOSITORY_BRANCH "${REPOSITORY_BRANCH}"
fi
NRB_CONFIG_ROOT="${CONFIG_ROOT}" "${APP_ROOT}/deploy/single-server/serverctl" provision

# Persist the operator-supplied identity. Everything else — session/auth secrets,
# encryption keys, Postgres/Redis/Grafana passwords, bot webhook secrets — is
# generated by `serverctl` and never needs to be typed.
if [[ -n "${PUBLIC_DOMAIN_INPUT}" ]]; then
  upsert_environment_value "${PRODUCTION_ENV}" PUBLIC_DOMAIN "${PUBLIC_DOMAIN_INPUT}"
  upsert_environment_value "${SERVER_ENV}" CERTIFICATE_NAME "${PUBLIC_DOMAIN_INPUT}"
fi
[[ -z "${CERTBOT_EMAIL_INPUT}" ]] || upsert_environment_value "${SERVER_ENV}" CERTBOT_EMAIL "${CERTBOT_EMAIL_INPUT}"
[[ -z "${IMAGE_REGISTRY_INPUT}" ]] || upsert_environment_value "${PRODUCTION_ENV}" IMAGE_REGISTRY "${IMAGE_REGISTRY_INPUT}"
[[ -z "${IMAGE_TAG_INPUT}" ]] || upsert_environment_value "${PRODUCTION_ENV}" IMAGE_TAG "${IMAGE_TAG_INPUT}"

if [[ "${APPLY_AFTER_BOOTSTRAP}" == 'true' ]]; then
  if [[ "${RUNTIME_MODE_INPUT}" == 'native' ]]; then
    printf 'Converging the host (data services, build, nginx, certificates, migrations, processes)...\n'
  else
    printf 'Converging the host (nginx, certificates, migrations, containers)...\n'
  fi
  NRB_CONFIG_ROOT="${CONFIG_ROOT}" "${APP_ROOT}/deploy/single-server/serverctl" apply
  cat <<EOF

Deployment complete. https://${PUBLIC_DOMAIN_INPUT} is live.

Inspect it with: sudo /usr/local/sbin/nrb-server doctor
EOF
  exit 0
fi

cat <<EOF
Bootstrap completed without deploying placeholder configuration.

1. Edit ${CONFIG_ROOT}/server.env.
2. Edit ${CONFIG_ROOT}/.env.production and its secret files.
3. Create the documented DNS records.
4. Run: sudo /usr/local/sbin/nrb-server apply

Every generatable secret is already created; only externally issued values
(provider tokens, an external DATABASE_URL) need to be pasted.

Rerunning this bootstrap is safe: it fast-forwards a clean checkout and
converges already-installed prerequisites instead of recreating configuration.
EOF
