// Generated by `pnpm nrb i18n catalogs`. Do not edit by hand.
import enAdminAuditCatalog from '@app/i18n-en-admin/audit.json';
import enAdminDashboardCatalog from '@app/i18n-en-admin/dashboard.json';
import enAdminFeatureFlagsCatalog from '@app/i18n-en-admin/feature-flags.json';
import enAdminLoginAnalyticsCatalog from '@app/i18n-en-admin/login-analytics.json';
import enAdminNavigationCatalog from '@app/i18n-en-admin/navigation.json';
import enAdminNotificationNavigationCatalog from '@app/i18n-en-admin/notification-navigation.json';
import enAdminNotificationOptionsCatalog from '@app/i18n-en-admin/notification-options.json';
import enAdminNotificationsCatalog from '@app/i18n-en-admin/notifications.json';
import enAdminProblemPresentationsCatalog from '@app/i18n-en-admin/problem-presentations.json';
import enAdminRolesCatalog from '@app/i18n-en-admin/roles.json';
import enAdminShellCatalog from '@app/i18n-en-admin/shell.json';
import enAdminUsersCatalog from '@app/i18n-en-admin/users.json';
import enCommonErrorsCatalog from '@app/i18n-en-common/errors.json';
import enCommonSharedCatalog from '@app/i18n-en-common/shared.json';
import ruAdminAuditCatalog from '@app/i18n-ru-admin/audit.json';
import ruAdminDashboardCatalog from '@app/i18n-ru-admin/dashboard.json';
import ruAdminFeatureFlagsCatalog from '@app/i18n-ru-admin/feature-flags.json';
import ruAdminLoginAnalyticsCatalog from '@app/i18n-ru-admin/login-analytics.json';
import ruAdminNavigationCatalog from '@app/i18n-ru-admin/navigation.json';
import ruAdminNotificationNavigationCatalog from '@app/i18n-ru-admin/notification-navigation.json';
import ruAdminNotificationOptionsCatalog from '@app/i18n-ru-admin/notification-options.json';
import ruAdminNotificationsCatalog from '@app/i18n-ru-admin/notifications.json';
import ruAdminProblemPresentationsCatalog from '@app/i18n-ru-admin/problem-presentations.json';
import ruAdminRolesCatalog from '@app/i18n-ru-admin/roles.json';
import ruAdminShellCatalog from '@app/i18n-ru-admin/shell.json';
import ruAdminUsersCatalog from '@app/i18n-ru-admin/users.json';
import ruCommonErrorsCatalog from '@app/i18n-ru-common/errors.json';
import ruCommonSharedCatalog from '@app/i18n-ru-common/shared.json';
import type { Locale, RuntimeLocaleCatalogFileEntry } from '@app/common-i18n-runtime';

export const catalogFileNames = [
  'admin/audit.json',
  'admin/dashboard.json',
  'admin/feature-flags.json',
  'admin/login-analytics.json',
  'admin/navigation.json',
  'admin/notification-navigation.json',
  'admin/notification-options.json',
  'admin/notifications.json',
  'admin/problem-presentations.json',
  'admin/roles.json',
  'admin/shell.json',
  'admin/users.json',
  'common/errors.json',
  'common/shared.json',
] as const;

export const localeCatalogFiles = {
  en: [
    ['admin/audit.json', enAdminAuditCatalog],
    ['admin/dashboard.json', enAdminDashboardCatalog],
    ['admin/feature-flags.json', enAdminFeatureFlagsCatalog],
    ['admin/login-analytics.json', enAdminLoginAnalyticsCatalog],
    ['admin/navigation.json', enAdminNavigationCatalog],
    ['admin/notification-navigation.json', enAdminNotificationNavigationCatalog],
    ['admin/notification-options.json', enAdminNotificationOptionsCatalog],
    ['admin/notifications.json', enAdminNotificationsCatalog],
    ['admin/problem-presentations.json', enAdminProblemPresentationsCatalog],
    ['admin/roles.json', enAdminRolesCatalog],
    ['admin/shell.json', enAdminShellCatalog],
    ['admin/users.json', enAdminUsersCatalog],
    ['common/errors.json', enCommonErrorsCatalog],
    ['common/shared.json', enCommonSharedCatalog],
  ],
  ru: [
    ['admin/audit.json', ruAdminAuditCatalog],
    ['admin/dashboard.json', ruAdminDashboardCatalog],
    ['admin/feature-flags.json', ruAdminFeatureFlagsCatalog],
    ['admin/login-analytics.json', ruAdminLoginAnalyticsCatalog],
    ['admin/navigation.json', ruAdminNavigationCatalog],
    ['admin/notification-navigation.json', ruAdminNotificationNavigationCatalog],
    ['admin/notification-options.json', ruAdminNotificationOptionsCatalog],
    ['admin/notifications.json', ruAdminNotificationsCatalog],
    ['admin/problem-presentations.json', ruAdminProblemPresentationsCatalog],
    ['admin/roles.json', ruAdminRolesCatalog],
    ['admin/shell.json', ruAdminShellCatalog],
    ['admin/users.json', ruAdminUsersCatalog],
    ['common/errors.json', ruCommonErrorsCatalog],
    ['common/shared.json', ruCommonSharedCatalog],
  ],
} as const satisfies Record<Locale, readonly RuntimeLocaleCatalogFileEntry[]>;
