// Generated by `pnpm nrb setup`. Do not edit by hand.
//
// Migrations owned by a selected capability rather than by the base schema.
// Empty when no selected capability contributes migrations, which is what keeps
// an unselected capability's DDL off every other project's database.
import type { MigrationObject } from '@mikro-orm/core';

// <nrb-generated-capability-migration-imports>
import { Migration20260823100000CreatePaymentProviders } from '../../../../../libs/backend/postgres/main/payments/lib/src/infrastructure/data-access/migrations/Migration20260823100000CreatePaymentProviders.ts';
import { Migration20260823100100CreatePayments } from '../../../../../libs/backend/postgres/main/payments/lib/src/infrastructure/data-access/migrations/Migration20260823100100CreatePayments.ts';
import { Migration20260823100200CreatePaymentEvents } from '../../../../../libs/backend/postgres/main/payments/lib/src/infrastructure/data-access/migrations/Migration20260823100200CreatePaymentEvents.ts';
import { Migration20260823100300CreatePaymentWebhookReceipts } from '../../../../../libs/backend/postgres/main/payments/lib/src/infrastructure/data-access/migrations/Migration20260823100300CreatePaymentWebhookReceipts.ts';
import { Migration20260827100000AddPaymentWebhookClaimLease } from '../../../../../libs/backend/postgres/main/payments/lib/src/infrastructure/data-access/migrations/Migration20260827100000AddPaymentWebhookClaimLease.ts';
// </nrb-generated-capability-migration-imports>

export const capabilityMigrations: readonly MigrationObject[] = [
  // <nrb-generated-capability-migration-entries>
  { class: Migration20260823100000CreatePaymentProviders, name: 'Migration20260823100000CreatePaymentProviders' },
  { class: Migration20260823100100CreatePayments, name: 'Migration20260823100100CreatePayments' },
  { class: Migration20260823100200CreatePaymentEvents, name: 'Migration20260823100200CreatePaymentEvents' },
  { class: Migration20260823100300CreatePaymentWebhookReceipts, name: 'Migration20260823100300CreatePaymentWebhookReceipts' },
  { class: Migration20260827100000AddPaymentWebhookClaimLease, name: 'Migration20260827100000AddPaymentWebhookClaimLease' },
  // </nrb-generated-capability-migration-entries>
];
