// Generated by `pnpm nrb setup`. Do not edit by hand.
//
// Migrations owned by a selected capability rather than by the base schema.
// Empty when no selected capability contributes migrations, which is what keeps
// an unselected capability's DDL off every other project's database.
import type { MigrationObject } from '@mikro-orm/core';

// <nrb-generated-capability-migration-imports>
// </nrb-generated-capability-migration-imports>

export const capabilityMigrations: readonly MigrationObject[] = [
  // <nrb-generated-capability-migration-entries>
  // </nrb-generated-capability-migration-entries>
];
