export const ProtectedLoggerFields = [
  'authorization',
  'cookie',
  'set-cookie',
  'password',
  'passwd',
  'pwd',
  'token',
  'access-token',
  'access_token',
  'refresh-token',
  'refresh_token',
  'id-token',
  'id_token',
  'signature',
  'x-signature',
  'x-api-key',
  'api-key',
  'api_key',
  'apikey',
  'access_key',
  'secret',
  'client-secret',
  'client_secret',
  'private-key',
  'private_key',
  'session',
  'sid',
  'csrf',
  'xsrf',
] as const;

export const RedactedValue = '[redacted]';
