services:
  backend-admin-app-api:
    build:
      context: ..
      dockerfile: Dockerfile
      target: backend
      args:
        NX_PROJECT: backend-admin-app-api
        BUILD_OUTPUT: dist/apps/backend/admin-app-api
    environment:
      NODE_ENV: production
      PORT: 3000
      CORS_ORIGINS: http://localhost:8081,http://localhost:8082,http://localhost:8083
    ports:
      - "3001:3000"

  user-app-api:
    build:
      context: ..
      dockerfile: Dockerfile
      target: backend
      args:
        NX_PROJECT: user-app-api
        BUILD_OUTPUT: dist/apps/backend/user-app-api
    environment:
      NODE_ENV: production
      PORT: 3000
      CORS_ORIGINS: http://localhost:8081,http://localhost:8082,http://localhost:8083
    ports:
      - "3002:3000"

  auth-app-api:
    build:
      context: ..
      dockerfile: Dockerfile
      target: backend
      args:
        NX_PROJECT: auth-app-api
        BUILD_OUTPUT: dist/apps/backend/auth-app-api
    environment:
      NODE_ENV: production
      PORT: 3000
      CORS_ORIGINS: http://localhost:8081,http://localhost:8082,http://localhost:8083
    ports:
      - "3003:3000"

  admin-app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: frontend
      args:
        NX_PROJECT: admin-app
        FRONTEND_OUTPUT: dist/apps/frontend/admin
    ports:
      - "8081:80"

  user-app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: frontend
      args:
        NX_PROJECT: user-app
        FRONTEND_OUTPUT: dist/apps/frontend/app
    ports:
      - "8082:80"

  landing-app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: frontend
      args:
        NX_PROJECT: landing-app
        FRONTEND_OUTPUT: dist/apps/frontend/landing
    ports:
      - "8083:80"
