import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

import {
  closureLockMetadataPath,
  closureLockPath,
  closureManifestPath,
  closurePackagePath,
  closureWorkspacePath,
  renderSelectedClosure,
  type SelectedClosureManifest,
} from './closure.js';
import { hashString } from './state.js';
import { appCatalog } from './catalog.js';

export interface ClosureArtifacts {
  caddyfile: { path: string; content: string };
  singleDomainCaddyfile: { path: string; content: string };
  manifest: { path: string; content: string };
  helmValues: { path: string; content: string };
  packageManifest: { path: string; content: string };
  workspaceManifest: { path: string; content: string };
}

export interface ClosureSyncResult {
  changed: boolean;
  invalidatedLock: boolean;
  artifacts: ClosureArtifacts;
}

export const normalizedClosureContextFiles = [
  'closure.json',
  'nrb.config.json',
  'workspace.json',
  'package.json',
  'pnpm-workspace.yaml',
  'pnpm-lock.yaml',
  'lock.json',
] as const;

export const closureHelmValuesPath = '.helm/values-selection.yaml';
export const closureCaddyfilePath = '.nrb/Caddyfile.per-app-domains';
export const closureSingleDomainCaddyfilePath = '.nrb/Caddyfile.single-domain';

export function renderClosureArtifacts(workspaceRoot: string, closure: SelectedClosureManifest): ClosureArtifacts {
  const rootPackage = JSON.parse(readFileSync(join(workspaceRoot, 'package.json'), 'utf8')) as {
    packageManager?: string;
    engines?: Record<string, string>;
  };
  const packageManifest = {
    name: '@nrb/selected-closure',
    version: '0.0.0',
    private: true,
    packageManager: rootPackage.packageManager,
    engines: rootPackage.engines,
    dependencies: closure.productExternalPackages ?? {},
    devDependencies: closure.toolingExternalPackages ?? {},
    nrb: {
      configHash: closure.configHash,
      graphDigest: closure.graphDigest,
    },
  };

  return {
    caddyfile: { path: closureCaddyfilePath, content: renderClosureCaddyfile(closure) },
    singleDomainCaddyfile: {
      path: closureSingleDomainCaddyfilePath,
      content: renderClosureSingleDomainCaddyfile(closure),
    },
    manifest: { path: closureManifestPath, content: renderSelectedClosure(closure) },
    helmValues: { path: closureHelmValuesPath, content: renderClosureHelmValues(closure) },
    packageManifest: { path: closurePackagePath, content: `${JSON.stringify(packageManifest, null, 2)}\n` },
    workspaceManifest: {
      path: closureWorkspacePath,
      content: renderClosureWorkspace(readFileSync(join(workspaceRoot, 'pnpm-workspace.yaml'), 'utf8')),
    },
  };
}

export function renderClosureCaddyfile(closure: SelectedClosureManifest): string {
  const selected = new Set(closure.releaseImages);
  const lines = [
    '# Generated by pnpm nrb setup from .nrb/closure.json. Do not edit.',
    'import /etc/caddy/common.caddy',
    '',
    '(frontend_service) {',
    '\timport common_server',
    ...(selected.has('auth-app-api') ? ['\timport /etc/caddy/routes/core/auth.caddy'] : []),
    ...(selected.has('user-app-api') ? ['\timport /etc/caddy/routes/core/user.caddy'] : []),
    ...(selected.has('admin-app-api') ? ['\timport /etc/caddy/routes/core/admin.caddy'] : []),
    '\timport /etc/caddy/routes/optional/{$EDGE_OPTIONAL_ROUTES:default}.caddy',
    '\thandle {',
    '\t\treverse_proxy {args[0]}',
    '\t}',
    '\timport /etc/caddy/tls/{$EDGE_TLS_MODE:automatic}.caddy',
    '}',
    '',
    '(api_service) {',
    '\timport common_server',
    '\treverse_proxy {args[0]}',
    '\timport /etc/caddy/tls/{$EDGE_TLS_MODE:automatic}.caddy',
    '}',
  ];
  for (const app of Object.values(appCatalog)) {
    if (
      !selected.has(app.id) ||
      app.classification === 'optional' ||
      !app.publicHostname ||
      !app.releaseImage?.composePort
    ) {
      continue;
    }
    const domainVariable = `${app.id.replaceAll('-', '_').toUpperCase()}_DOMAIN`;
    lines.push(
      '',
      `{$${domainVariable}} {`,
      `\timport ${app.platform === 'frontend' ? 'frontend_service' : 'api_service'} ${app.id}:${app.releaseImage.composePort}`,
      '}',
    );
  }
  lines.push('', 'import /etc/caddy/sites/optional/{$EDGE_OPTIONAL_ROUTES:default}.caddy');
  return `${lines.join('\n')}\n`;
}

export function renderClosureSingleDomainCaddyfile(closure: SelectedClosureManifest): string {
  const selected = new Set(closure.releaseImages);
  const lines = [
    '# Generated by pnpm nrb setup from .nrb/closure.json. Do not edit.',
    'import /etc/caddy/common.caddy',
    '',
    '{$PUBLIC_DOMAIN} {',
    '\timport common_server',
  ];
  if (selected.has('auth-app-api')) {
    lines.push(
      '',
      '\t@auth_callbacks path /auth/discord/callback',
      '\thandle @auth_callbacks {',
      '\t\treverse_proxy auth-app-api:80',
      '\t}',
      '',
      '\t@oauth_api path /oauth /oauth/*',
      '\thandle @oauth_api {',
      '\t\treverse_proxy auth-app-api:80',
      '\t}',
      '',
      '\timport /etc/caddy/routes/core/auth.caddy',
    );
  }
  if (selected.has('user-app-api')) {
    lines.push('\timport /etc/caddy/routes/core/user.caddy');
  }
  if (selected.has('admin-app-api')) {
    lines.push('\timport /etc/caddy/routes/core/admin.caddy');
  }
  lines.push(
    '\timport /etc/caddy/routes/optional/{$EDGE_OPTIONAL_ROUTES:default}.caddy',
    '',
    '\thandle {',
    '\t\treverse_proxy {$PRIMARY_APP_UPSTREAM}',
    '\t}',
    '',
    '\timport /etc/caddy/tls/{$EDGE_TLS_MODE:automatic}.caddy',
    '}',
  );
  return `${lines.join('\n')}\n`;
}

export function renderClosureHelmValues(closure: SelectedClosureManifest): string {
  const selectedApps = closure.releaseImages.filter((image) => image !== 'migrator');
  const selected = new Set(selectedApps);
  const hasPublicApp = selectedApps.some((appId) => appCatalog[appId as keyof typeof appCatalog]?.publicHostname);
  const lines = [
    '# Generated by pnpm nrb setup from .nrb/closure.json. Do not edit.',
    'deployment:',
    '  selectedApps:',
    ...selectedApps.map((appId) => `    - ${appId}`),
    `  provider: ${closure.provider ?? "''"}`,
    'selection:',
    `  ciMode: ${closure.product.ciMode}`,
    `  frontendApiMode: ${closure.product.frontendApiMode}`,
    `  mobileTargets: [${closure.product.mobileTargets.join(', ')}]`,
    `  deploymentTargets: [${closure.deployment.targets.join(', ')}]`,
    `  publicTopology: ${closure.deployment.publicTopology}`,
    `  kubernetesDelivery: ${closure.deployment.kubernetesDelivery}`,
    '  infrastructure:',
    `    redis: ${closure.deployment.infrastructure.redis}`,
    `    nats: ${closure.deployment.infrastructure.nats}`,
    `    s3: ${closure.deployment.infrastructure.s3}`,
    'database:',
    `  engine: ${closure.provider ?? "''"}`,
    'migrations:',
    `  enabled: ${closure.provider !== null}`,
    ...(closure.projects.includes('@app/backend-common-otel')
      ? []
      : ['monitoring:', '  enabled: false', '  otel:', '    enabled: false', '  otelCollector:', '    enabled: false']),
    ...(hasPublicApp ? [] : ['ingress:', '  enabled: false']),
    'apps:',
  ];
  for (const app of Object.values(appCatalog)) {
    if (!app.releaseImage) {
      continue;
    }
    lines.push(`  ${app.releaseImage.helmValuesKey}:`, `    enabled: ${selected.has(app.id)}`);
  }
  return `${lines.join('\n')}\n`;
}

export function synchronizeClosureArtifacts(
  workspaceRoot: string,
  closure: SelectedClosureManifest,
): ClosureSyncResult {
  const artifacts = renderClosureArtifacts(workspaceRoot, closure);
  const changed = Object.values(artifacts).some(({ path, content }) => read(workspaceRoot, path) !== content);

  for (const { path, content } of Object.values(artifacts)) {
    const absolutePath = join(workspaceRoot, path);
    mkdirSync(dirname(absolutePath), { recursive: true });
    writeFileSync(absolutePath, content);
  }

  let invalidatedLock = false;
  if (changed) {
    for (const path of [closureLockPath, closureLockMetadataPath]) {
      const absolutePath = join(workspaceRoot, path);
      if (existsSync(absolutePath)) {
        rmSync(absolutePath);
        invalidatedLock = true;
      }
    }
  }

  return { changed, invalidatedLock, artifacts };
}

export function checkClosureArtifacts(
  workspaceRoot: string,
  closure: SelectedClosureManifest,
): { valid: boolean; problems: string[]; lockStatus: 'current' | 'missing' | 'stale' } {
  const artifacts = renderClosureArtifacts(workspaceRoot, closure);
  const problems = Object.values(artifacts)
    .filter(({ path, content }) => read(workspaceRoot, path) !== content)
    .map(({ path }) => `${path} is missing or stale`);
  return { valid: problems.length === 0, problems, lockStatus: readClosureLockStatus(workspaceRoot, closure) };
}

export function writeClosureLockMetadata(workspaceRoot: string, closure: SelectedClosureManifest): void {
  const lockPath = join(workspaceRoot, closureLockPath);
  if (!existsSync(lockPath)) {
    throw new Error(`${closureLockPath} was not generated by pnpm.`);
  }
  const metadataPath = join(workspaceRoot, closureLockMetadataPath);
  writeFileSync(
    metadataPath,
    `${JSON.stringify(
      {
        schemaVersion: 1,
        configHash: closure.configHash,
        graphDigest: closure.graphDigest,
        lockHash: hashString(readFileSync(lockPath, 'utf8')),
      },
      null,
      2,
    )}\n`,
  );
}

export function synchronizeProductClosureBuildContext(workspaceRoot: string, closure: SelectedClosureManifest): string {
  if (readClosureLockStatus(workspaceRoot, closure) !== 'current') {
    throw new Error('Selected closure lock is missing or stale; run `pnpm nrb closure install`.');
  }
  const contextRoot = resolve(workspaceRoot, '.nrb/closure');
  for (const [source, destination] of [
    [closureManifestPath, 'closure.json'],
    ['nrb.config.json', 'nrb.config.json'],
    ['.nrb/workspace.json', 'workspace.json'],
  ] as const) {
    const sourcePath = join(workspaceRoot, source);
    if (!existsSync(sourcePath)) {
      throw new Error(`Selected closure build context source is missing: ${source}`);
    }
    writeFileSync(join(contextRoot, destination), readFileSync(sourcePath, 'utf8'));
  }
  writeFileSync(join(contextRoot, '.dockerignore'), 'node_modules\n');
  return validateProductClosureBuildContext(workspaceRoot, closure);
}

export function validateProductClosureBuildContext(workspaceRoot: string, closure: SelectedClosureManifest): string {
  if (readClosureLockStatus(workspaceRoot, closure) !== 'current') {
    throw new Error('Selected closure lock is missing or stale; run `pnpm nrb closure install`.');
  }
  const contextRoot = resolve(workspaceRoot, '.nrb/closure');
  for (const file of normalizedClosureContextFiles) {
    if (!existsSync(join(contextRoot, file))) {
      throw new Error(`Selected nrb-closure build context is incomplete: ${file} is missing.`);
    }
  }
  for (const [source, destination] of [
    [closureManifestPath, 'closure.json'],
    ['nrb.config.json', 'nrb.config.json'],
    ['.nrb/workspace.json', 'workspace.json'],
  ] as const) {
    if (readFileSync(join(workspaceRoot, source), 'utf8') !== readFileSync(join(contextRoot, destination), 'utf8')) {
      throw new Error(`Selected nrb-closure build context is stale: ${destination} does not match ${source}.`);
    }
  }
  return contextRoot;
}

export function readClosureLockStatus(
  workspaceRoot: string,
  closure: SelectedClosureManifest,
): 'current' | 'missing' | 'stale' {
  const lockPath = join(workspaceRoot, closureLockPath);
  const metadataPath = join(workspaceRoot, closureLockMetadataPath);
  if (!existsSync(lockPath) || !existsSync(metadataPath)) {
    return 'missing';
  }
  try {
    const metadata = JSON.parse(readFileSync(metadataPath, 'utf8')) as Record<string, unknown>;
    return metadata.configHash === closure.configHash &&
      metadata.graphDigest === closure.graphDigest &&
      metadata.lockHash === hashString(readFileSync(lockPath, 'utf8'))
      ? 'current'
      : 'stale';
  } catch {
    return 'stale';
  }
}

export function renderClosureWorkspace(rootWorkspace: string): string {
  const lines = rootWorkspace.split(/\r?\n/u);
  const policyStart = lines.findIndex((line, index) => index > 0 && /^[a-zA-Z][\w-]*:/u.test(line));
  if (policyStart < 0) {
    throw new Error('pnpm-workspace.yaml must contain policy after its packages section.');
  }
  const policy = lines.slice(policyStart).join('\n').replace(/^\n+/u, '');
  return `packages:\n  - '.'\n\n${policy.trimEnd()}\n`;
}

function read(workspaceRoot: string, relativePath: string): string | undefined {
  const path = join(workspaceRoot, relativePath);
  return existsSync(path) ? readFileSync(path, 'utf8') : undefined;
}
