// Generated by `pnpm nrb setup`. Do not edit by hand.
import { Global, Module } from '@nestjs/common';

@Global()
@Module({ imports: [], exports: [] })
export class DiscordAppApiCapabilitiesModule {}
