// Generated by `pnpm nrb setup`. Do not edit by hand.
export function initializeCapabilities(serviceName: string): void {
  if (serviceName.length === 0) {
    throw new Error('Capability initialization requires a service name.');
  }
}
