// Generated by `pnpm nrb setup`. Do not edit by hand.
//
// This module wires only the capabilities the workspace selection turned on, and rerunning
// setup rewrites it whole. A product module belongs instead in the app's hand-written
// root module that imports it, which setup never rewrites.
import { Global, Module } from '@nestjs/common';
import { S3Module } from '@app/backend-common-s3';
import { NotificationMainModule } from '@app/backend-feature-notification-main';
import { PaymentsMainModule } from '@app/backend-feature-payments-main';
import { PostgresMainModule } from '@app/backend-postgres-main';
import { AuthPostgresModule } from '@app/backend-postgres-main-auth';
import { FeatureFlagsPostgresModule } from '@app/backend-postgres-main-feature-flags';
import { NotificationPostgresModule } from '@app/backend-postgres-main-notification';
import { PaymentsPostgresModule } from '@app/backend-postgres-main-payments';

@Global()
@Module({
  imports: [
    AuthPostgresModule,
    FeatureFlagsPostgresModule,
    NotificationMainModule.forRoot({ enableScheduler: false, exposeHttp: false }),
    NotificationPostgresModule,
    PaymentsMainModule.forRoot({ imports: [PaymentsPostgresModule], exposeHttp: true, scheduler: { enabled: true, intervalMs: 60_000 } }),
    PostgresMainModule.forRoot(),
    S3Module.forRoot(),
  ],
  exports: [
    AuthPostgresModule,
    FeatureFlagsPostgresModule,
    NotificationMainModule,
    NotificationPostgresModule,
    PaymentsMainModule,
    PostgresMainModule,
    S3Module,
  ],
})
export class AuthAppApiCapabilitiesModule {}
