#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"; import { createServer } from "node:http"; import { createReadStream } from "node:fs"; import { join, resolve } from "node:path";
const dryRun = process.argv.includes("--dry-run"); const out = "test-results/accessibility/report.json"; const urls = (process.env.A11Y_URLS ?? "").split(",").map((x) => x.trim()).filter(Boolean);
if (dryRun) { mkdirSync("test-results/accessibility", { recursive: true }); writeFileSync(out, JSON.stringify({ status: "dry-run", urls }, null, 2)); console.log(JSON.stringify({ status: "dry-run", preset: "accessibility" })); process.exit(0); }
async function serveDir(dir) { const root = resolve(dir); const server = createServer((req, res) => { const file = join(root, (req.url ?? "/").split("?")[0] === "/" ? "index.html" : (req.url ?? "/").split("?")[0]); if (!file.startsWith(root) || !existsSync(file)) { res.statusCode = 404; res.end("not found"); return; } createReadStream(file).pipe(res); }); await new Promise((r) => server.listen(0, "127.0.0.1", r)); return { url: `http://127.0.0.1:${server.address().port}`, close: () => new Promise((r) => server.close(r)) }; }
const servers = []; if (!urls.length) for (const dir of ["dist/apps/frontend/admin", "dist/apps/frontend/app", "dist/apps/frontend/landing", "dist/storybook/frontend-ui"]) if (existsSync(join(dir, "index.html"))) { const server = await serveDir(dir); servers.push(server); urls.push(server.url); }
const { chromium } = await import("@playwright/test"); const browser = await chromium.launch(); const results = [];
try { for (const url of urls) { const page = await browser.newPage(); await page.goto(url, { waitUntil: "networkidle" }); const semantic = await page.evaluate(() => ({ title: document.title, landmarks: document.querySelectorAll("main,nav,header,footer,aside").length, headings: document.querySelectorAll("h1,h2,h3,h4,h5,h6").length, imagesWithoutAlt: [...document.images].filter((img) => !img.hasAttribute("alt")).length, unlabeledInputs: [...document.querySelectorAll("input,select,textarea")].filter((el) => !el.labels?.length && !el.getAttribute("aria-label") && !el.getAttribute("aria-labelledby")).length, unnamedButtons: [...document.querySelectorAll("button")].filter((el) => !el.textContent?.trim() && !el.getAttribute("aria-label")).length })); let axe = null; if (existsSync("node_modules/axe-core/axe.min.js")) { await page.addScriptTag({ content: readFileSync("node_modules/axe-core/axe.min.js", "utf8") }); axe = await page.evaluate(() => globalThis.axe.run()); } results.push({ url, semantic, axeViolations: axe?.violations?.length ?? null, ok: Boolean(semantic.title) && semantic.headings > 0 && semantic.imagesWithoutAlt === 0 && semantic.unlabeledInputs === 0 && semantic.unnamedButtons === 0 && (axe ? axe.violations.length === 0 : true) }); await page.close(); } } finally { await browser.close(); for (const s of servers) await s.close(); }
mkdirSync("test-results/accessibility", { recursive: true }); writeFileSync(out, `${JSON.stringify({ status: results.every((r) => r.ok) ? "ok" : "violations", results }, null, 2)}\n`); console.log(JSON.stringify({ status: results.every((r) => r.ok) ? "ok" : "violations", report: out })); if (results.some((r) => !r.ok)) process.exit(1);
