// Generated by `pnpm nrb i18n catalogs`. Do not edit by hand.
import enBotsSharedCatalog from '@app/i18n-en-bots/shared.json';
import enBotsTelegramCatalog from '@app/i18n-en-bots/telegram.json';
import enCommonErrorsCatalog from '@app/i18n-en-common/errors.json';
import enCommonSharedCatalog from '@app/i18n-en-common/shared.json';
import ruBotsSharedCatalog from '@app/i18n-ru-bots/shared.json';
import ruBotsTelegramCatalog from '@app/i18n-ru-bots/telegram.json';
import ruCommonErrorsCatalog from '@app/i18n-ru-common/errors.json';
import ruCommonSharedCatalog from '@app/i18n-ru-common/shared.json';
import zhBotsSharedCatalog from '@app/i18n-zh-bots/shared.json';
import zhBotsTelegramCatalog from '@app/i18n-zh-bots/telegram.json';
import zhCommonErrorsCatalog from '@app/i18n-zh-common/errors.json';
import zhCommonSharedCatalog from '@app/i18n-zh-common/shared.json';
import type { Locale, RuntimeLocaleCatalogFileEntry } from '@app/common-i18n-runtime';

export const catalogFileNames = [
  'bots/shared.json',
  'bots/telegram.json',
  'common/errors.json',
  'common/shared.json',
] as const;

export const localeCatalogFiles = {
  en: [
    ['bots/shared.json', enBotsSharedCatalog],
    ['bots/telegram.json', enBotsTelegramCatalog],
    ['common/errors.json', enCommonErrorsCatalog],
    ['common/shared.json', enCommonSharedCatalog],
  ],
  ru: [
    ['bots/shared.json', ruBotsSharedCatalog],
    ['bots/telegram.json', ruBotsTelegramCatalog],
    ['common/errors.json', ruCommonErrorsCatalog],
    ['common/shared.json', ruCommonSharedCatalog],
  ],
  zh: [
    ['bots/shared.json', zhBotsSharedCatalog],
    ['bots/telegram.json', zhBotsTelegramCatalog],
    ['common/errors.json', zhCommonErrorsCatalog],
    ['common/shared.json', zhCommonSharedCatalog],
  ],
} as const satisfies Record<Locale, readonly RuntimeLocaleCatalogFileEntry[]>;
