// Generated by `pnpm nrb setup`. Do not edit by hand.
//
// This module wires only the capabilities the workspace selection turned on, and rerunning
// setup rewrites it whole. A product module belongs instead in the app's hand-written
// root module that imports it, which setup never rewrites.
import { Global, Module } from '@nestjs/common';

@Global()
@Module({ imports: [], exports: [] })
export class TelegramBotApiCapabilitiesModule {}
