// Generated by `pnpm nrb setup`. Do not edit by hand.
//
// This module wires only the capabilities the workspace selection turned on, and rerunning
// setup rewrites it whole. A product module belongs instead in the app's hand-written
// root module that imports it, which setup never rewrites.
import { Global, Module } from '@nestjs/common';
import { RedisModule } from '@app/backend-common-redis';
import { S3Module } from '@app/backend-common-s3';
import { PaymentsMainModule } from '@app/backend-feature-payments-main';
import { PaymentsPostgresModule } from '@app/backend-postgres-main-payments';

@Global()
@Module({
  imports: [
    PaymentsMainModule.forRoot({ imports: [PaymentsPostgresModule], exposeHttp: true, scheduler: { enabled: true, intervalMs: 60_000 } }),
    RedisModule.forRoot(),
    S3Module.forRoot(),
  ],
  exports: [PaymentsMainModule, RedisModule, S3Module],
})
export class TelegramBotApiCapabilitiesModule {}
