// Generated by `pnpm nrb i18n catalogs`. Do not edit by hand.
import enCommonErrorsCatalog from '@app/i18n-en-common/errors.json';
import enCommonSharedCatalog from '@app/i18n-en-common/shared.json';
import enUserAuthCatalog from '@app/i18n-en-user/auth.json';
import enUserMobileCatalog from '@app/i18n-en-user/mobile.json';
import enUserShellCatalog from '@app/i18n-en-user/shell.json';
import enUserSiteCatalog from '@app/i18n-en-user/site.json';
import enUserSocialAuthCatalog from '@app/i18n-en-user/social-auth.json';
import enUserTmaCatalog from '@app/i18n-en-user/tma.json';
import ruCommonErrorsCatalog from '@app/i18n-ru-common/errors.json';
import ruCommonSharedCatalog from '@app/i18n-ru-common/shared.json';
import ruUserAuthCatalog from '@app/i18n-ru-user/auth.json';
import ruUserMobileCatalog from '@app/i18n-ru-user/mobile.json';
import ruUserShellCatalog from '@app/i18n-ru-user/shell.json';
import ruUserSiteCatalog from '@app/i18n-ru-user/site.json';
import ruUserSocialAuthCatalog from '@app/i18n-ru-user/social-auth.json';
import ruUserTmaCatalog from '@app/i18n-ru-user/tma.json';
import type { Locale, RuntimeLocaleCatalogFileEntry } from '@app/common-i18n-runtime';

export const catalogFileNames = [
  'common/errors.json',
  'common/shared.json',
  'user/auth.json',
  'user/mobile.json',
  'user/shell.json',
  'user/site.json',
  'user/social-auth.json',
  'user/tma.json',
] as const;

export const localeCatalogFiles = {
  en: [
    ['common/errors.json', enCommonErrorsCatalog],
    ['common/shared.json', enCommonSharedCatalog],
    ['user/auth.json', enUserAuthCatalog],
    ['user/mobile.json', enUserMobileCatalog],
    ['user/shell.json', enUserShellCatalog],
    ['user/site.json', enUserSiteCatalog],
    ['user/social-auth.json', enUserSocialAuthCatalog],
    ['user/tma.json', enUserTmaCatalog],
  ],
  ru: [
    ['common/errors.json', ruCommonErrorsCatalog],
    ['common/shared.json', ruCommonSharedCatalog],
    ['user/auth.json', ruUserAuthCatalog],
    ['user/mobile.json', ruUserMobileCatalog],
    ['user/shell.json', ruUserShellCatalog],
    ['user/site.json', ruUserSiteCatalog],
    ['user/social-auth.json', ruUserSocialAuthCatalog],
    ['user/tma.json', ruUserTmaCatalog],
  ],
} as const satisfies Record<Locale, readonly RuntimeLocaleCatalogFileEntry[]>;
