{{- $root := . -}}
{{- range $name, $app := .Values.apps }}
{{- if $app.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "boilerplate.fullname" $root }}-{{ kebabcase $name }}
  labels:
    {{- include "boilerplate.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ kebabcase $name }}
spec:
  replicas: {{ $app.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $root.Release.Name }}
      app.kubernetes.io/component: {{ kebabcase $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ $root.Release.Name }}
        app.kubernetes.io/component: {{ kebabcase $name }}
    spec:
      {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ kebabcase $name }}
          image: {{ printf "%s:%s" $app.image.repository $app.image.tag | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ $app.port }}
          envFrom:
            - configMapRef:
                name: {{ include "boilerplate.fullname" $root }}-config
            - secretRef:
                name: {{ include "boilerplate.secretName" $root }}
          readinessProbe:
            httpGet:
              path: {{ ternary "/ready" "/" (contains "Api" $name) }}
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ ternary "/live" "/" (contains "Api" $name) }}
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml $app.resources | nindent 12 }}
{{- end }}
{{- end }}
