{{- if .Values.autoscaling.enabled }}
{{- $root := . -}}
{{- range $name, $app := .Values.apps }}
{{- if and $app.enabled (ne $app.kind "background") }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "boilerplate.fullname" $root }}-{{ kebabcase $name }}
  labels:
    {{- include "boilerplate.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ kebabcase $name }}
spec:
  minReplicas: {{ $root.Values.autoscaling.minReplicas }}
  maxReplicas: {{ $root.Values.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "boilerplate.fullname" $root }}-{{ kebabcase $name }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $root.Values.autoscaling.targetCPUUtilization }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ default 300 $.Values.autoscaling.scaleDownStabilizationWindow }}
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: {{ default 0 $.Values.autoscaling.scaleUpStabilizationWindow }}
{{- end }}
{{- end }}
{{- end }}
