{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "boilerplate.fullname" . }}
  labels:
    {{- include "boilerplate.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host.host | quote }}
      http:
        paths:
          {{- range $path := $host.paths }}
          - path: {{ $path | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "boilerplate.fullname" $ }}-{{ $host.service }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
