{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "boilerplate.fullname" . }}-migrate
  labels:
    {{- include "boilerplate.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: {{ printf "%s:%s" .Values.migrations.image.repository .Values.migrations.image.tag | quote }}
          command: {{ toJson .Values.migrations.command }}
          envFrom:
            - configMapRef:
                name: {{ include "boilerplate.fullname" . }}-config
            - secretRef:
                name: {{ include "boilerplate.secretName" . }}
{{- end }}
