{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled .Values.monitoring.otelCollector.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "boilerplate.fullname" . }}-otel-collector
  labels:
    {{- include "boilerplate.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "boilerplate.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: otel-collector
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  endpoints:
    - port: prometheus
      path: /metrics
      interval: {{ default "30s" .Values.monitoring.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ default "10s" .Values.monitoring.serviceMonitor.scrapeTimeout | quote }}
{{- end }}
