{{- $root := . -}}
{{- range $name, $app := .Values.apps }}
{{- if $app.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "boilerplate.fullname" $root }}-{{ kebabcase $name }}
  labels:
    {{- include "boilerplate.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ kebabcase $name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "boilerplate.name" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/component: {{ kebabcase $name }}
  ports:
    - name: http
      port: {{ default $app.port $app.servicePort }}
      targetPort: http
{{- end }}
{{- end }}
