// Generated by `pnpm nrb i18n catalogs`. Do not edit by hand.
import enBotsDiscordCatalog from '@app/i18n-en-bots/discord.json';
import enBotsSharedCatalog from '@app/i18n-en-bots/shared.json';
import enCommonErrorsCatalog from '@app/i18n-en-common/errors.json';
import enCommonSharedCatalog from '@app/i18n-en-common/shared.json';
import ruBotsDiscordCatalog from '@app/i18n-ru-bots/discord.json';
import ruBotsSharedCatalog from '@app/i18n-ru-bots/shared.json';
import ruCommonErrorsCatalog from '@app/i18n-ru-common/errors.json';
import ruCommonSharedCatalog from '@app/i18n-ru-common/shared.json';
import zhBotsDiscordCatalog from '@app/i18n-zh-bots/discord.json';
import zhBotsSharedCatalog from '@app/i18n-zh-bots/shared.json';
import zhCommonErrorsCatalog from '@app/i18n-zh-common/errors.json';
import zhCommonSharedCatalog from '@app/i18n-zh-common/shared.json';
import type { Locale, RuntimeLocaleCatalogFileEntry } from '@app/common-i18n-runtime';

export const catalogFileNames = [
  'bots/discord.json',
  'bots/shared.json',
  'common/errors.json',
  'common/shared.json',
] as const;

export const localeCatalogFiles = {
  en: [
    ['bots/discord.json', enBotsDiscordCatalog],
    ['bots/shared.json', enBotsSharedCatalog],
    ['common/errors.json', enCommonErrorsCatalog],
    ['common/shared.json', enCommonSharedCatalog],
  ],
  ru: [
    ['bots/discord.json', ruBotsDiscordCatalog],
    ['bots/shared.json', ruBotsSharedCatalog],
    ['common/errors.json', ruCommonErrorsCatalog],
    ['common/shared.json', ruCommonSharedCatalog],
  ],
  zh: [
    ['bots/discord.json', zhBotsDiscordCatalog],
    ['bots/shared.json', zhBotsSharedCatalog],
    ['common/errors.json', zhCommonErrorsCatalog],
    ['common/shared.json', zhCommonSharedCatalog],
  ],
} as const satisfies Record<Locale, readonly RuntimeLocaleCatalogFileEntry[]>;
