// @requirements REQ-SCAFFOLD-TOOLING-005
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { after, describe, it } from "node:test";

import { defaultLocale, supportedLocales } from "@app/common-i18n-runtime";

import {
  discoverCatalogNamespaces,
  discoverLocaleCatalogFiles,
  discoverLocaleScopes,
  isLocaleMetadataFile,
} from "./catalog-sources.ts";
import {
  checkLocaleCatalogBindings,
  localeCatalogBindings,
  renderLocaleCatalogBinding,
} from "./catalog-bindings.ts";
import {
  checkTranslationKeyModule,
  collectCatalogTranslationKeys,
  renderTranslationKeyModule,
  translationKeyModulePath,
} from "./translation-keys.ts";

const workspaceRoot = resolve(import.meta.dirname, "../../../../..");
const temporaryRoots: string[] = [];

function fixtureWorkspace(): string {
  const root = mkdtempSync(join(tmpdir(), "i18n-catalog-"));
  temporaryRoots.push(root);
  mkdirSync(join(root, "i18n/xx/common"), { recursive: true });
  mkdirSync(join(root, "i18n/xx/admin"), { recursive: true });
  writeFileSync(join(root, "i18n/xx/common/shared.json"), '{"common.ready": "Ready"}\n');
  writeFileSync(join(root, "i18n/xx/common/errors.json"), '{"errors.unknown": "Unknown"}\n');
  writeFileSync(join(root, "i18n/xx/common/project.json"), '{"name": "@app/i18n-xx-common"}\n');
  writeFileSync(join(root, "i18n/xx/admin/shell.json"), '{"admin.shell.title": "Admin"}\n');
  writeFileSync(join(root, "i18n/xx/untranslated-allowlist.json"), '{"keys": []}\n');
  return root;
}

after(() => {
  for (const root of temporaryRoots) {
    rmSync(root, { force: true, recursive: true });
  }
});

describe("locale catalog discovery", () => {
  it("discovers namespaces without an allowlist and skips manifests and locale metadata", () => {
    const root = fixtureWorkspace();

    assert.deepEqual(discoverLocaleScopes(root, "xx"), ["admin", "common"]);
    assert.deepEqual(discoverLocaleCatalogFiles(root, "xx"), [
      "admin/shell.json",
      "common/errors.json",
      "common/shared.json",
    ]);
  });

  it("restricts discovery to the scopes a binding consumes", () => {
    const root = fixtureWorkspace();

    assert.deepEqual(discoverLocaleCatalogFiles(root, "xx", ["common"]), [
      "common/errors.json",
      "common/shared.json",
    ]);
    assert.deepEqual(discoverLocaleCatalogFiles(root, "xx", ["nonexistent"]), []);
  });

  it("narrows a selector to one catalog of a scope several consumers share", () => {
    const root = fixtureWorkspace();

    assert.deepEqual(
      discoverLocaleCatalogFiles(root, "xx", ["common/shared.json", "admin"]),
      ["admin/shell.json", "common/shared.json"],
    );
    assert.deepEqual(discoverLocaleCatalogFiles(root, "xx", ["common/absent.json"]), []);
  });

  it("treats a file at the locale root as metadata rather than a catalog", () => {
    assert.equal(isLocaleMetadataFile("untranslated-allowlist.json"), true);
    assert.equal(isLocaleMetadataFile("common/shared.json"), false);
  });

  it("returns nothing for a locale that has no catalog tree", () => {
    const root = fixtureWorkspace();

    assert.deepEqual(discoverLocaleScopes(root, "zz"), []);
    assert.deepEqual(discoverLocaleCatalogFiles(root, "zz"), []);
  });

  it("takes the required namespace set from the default locale of the real workspace", () => {
    const namespaces = discoverCatalogNamespaces(workspaceRoot, defaultLocale);

    assert.ok(namespaces.includes("common/shared.json"));
    assert.equal(
      namespaces.some((namespace) => namespace.endsWith("/project.json")),
      false,
    );
  });
});

describe("translation key module", () => {
  it("renders every default-locale catalog key as a sorted union under a generated header", () => {
    const rendered = renderTranslationKeyModule(["b.two", "a.one", "a.one"]);

    assert.match(rendered, /^\/\/ Generated by /u);
    assert.match(rendered, /export type TranslationKey =\n {2}\| 'a\.one'\n {2}\| 'b\.two';\n$/u);
  });

  it("collects the union members from the catalogs rather than from the checked-in type", () => {
    const keys = collectCatalogTranslationKeys(workspaceRoot, defaultLocale);

    assert.ok(keys.includes("common.ready"));
    assert.deepEqual([...keys].sort((left, right) => left.localeCompare(right)), keys);
  });

  it("keeps the checked-in union identical to the generated one", () => {
    assert.deepEqual(checkTranslationKeyModule(workspaceRoot), []);
    assert.equal(translationKeyModulePath, "libs/common/i18n/keys/lib/src/index.ts");
  });
});

describe("locale catalog bindings", () => {
  it("binds every configured locale for every discovered namespace", () => {
    const binding = localeCatalogBindings.find((candidate) => candidate.id === "frontend-shared");
    assert.ok(binding);

    const rendered = renderLocaleCatalogBinding(workspaceRoot, binding);

    for (const locale of supportedLocales) {
      assert.ok(
        rendered.includes(`from '@app/i18n-${locale}-common/shared.json'`),
        `${locale} shared catalog is not imported`,
      );
      assert.match(rendered, new RegExp(`^ {2}'?${locale}'?: \\[$`, "mu"), `${locale} has no registry entry`);
    }
    assert.match(rendered, /satisfies Record<Locale, readonly RuntimeLocaleCatalogFileEntry\[\]>/u);
  });

  it("keeps every checked-in binding identical to the generated one", () => {
    assert.deepEqual(checkLocaleCatalogBindings(workspaceRoot), []);
  });

  it("generates the bot catalog modules from the registry, each bound to its own bot catalog", () => {
    for (const { id, own, foreign } of [
      { foreign: "telegram", id: "backend-discord", own: "discord" },
      { foreign: "discord", id: "backend-telegram", own: "telegram" },
    ]) {
      const binding = localeCatalogBindings.find((candidate) => candidate.id === id);
      assert.ok(binding, `${id} is not registered`);

      const rendered = renderLocaleCatalogBinding(workspaceRoot, binding);

      for (const locale of supportedLocales) {
        assert.ok(
          rendered.includes(`from '@app/i18n-${locale}-bots/${own}.json'`),
          `${id} does not import the ${locale} ${own} catalog`,
        );
        assert.ok(
          rendered.includes(`from '@app/i18n-${locale}-common/errors.json'`),
          `${id} does not import the ${locale} common errors catalog`,
        );
      }
      assert.equal(
        rendered.includes(`bots/${foreign}.json`),
        false,
        `${id} binds the ${foreign} bot's catalog`,
      );
    }
  });

  it("reports every unregenerated binding instead of rewriting it during a check", () => {
    const binding = localeCatalogBindings[0];
    assert.ok(binding);

    const root = mkdtempSync(join(tmpdir(), "i18n-binding-"));
    temporaryRoots.push(root);
    mkdirSync(join(root, "i18n", defaultLocale, "common"), { recursive: true });
    writeFileSync(join(root, "i18n", defaultLocale, "common/shared.json"), "{}\n");

    const failures = checkLocaleCatalogBindings(root);

    assert.equal(failures.length, localeCatalogBindings.length);
    assert.match(failures[0] ?? "", /run `pnpm nrb i18n catalogs`/u);
  });
});
