import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { supportedLocales } from "@app/common-i18n-runtime";

import { discoverLocaleCatalogFiles } from "./catalog-sources.ts";

export interface LocaleCatalogBinding {
  readonly id: string;
  /** Workspace-relative path of the generated module. */
  readonly outputPath: string;
  /** Catalog scopes this consumer merges. The scope list is the ONLY hand-maintained axis left. */
  readonly scopes: readonly string[];
}

/**
 * Which catalog scopes each consumer binds. Neither the locale axis nor the namespace axis appears
 * here: locales come from `supportedLocales` and namespaces are discovered from the catalog tree, so
 * adding either is a file drop plus a regeneration rather than an edit to every binding module.
 */
export const localeCatalogBindings: readonly LocaleCatalogBinding[] = [
  {
    id: "backend-common",
    outputPath: "libs/backend/common/i18n/lib/src/catalogs.generated.ts",
    scopes: ["common"],
  },
  {
    id: "frontend-shared",
    outputPath: "libs/frontend/i18n/shared/lib/src/catalogs.generated.ts",
    scopes: ["common"],
  },
  {
    id: "frontend-landing",
    outputPath: "libs/frontend/feature/landing/i18n/lib/src/catalogs.generated.ts",
    scopes: ["common", "landing"],
  },
  {
    id: "frontend-admin",
    outputPath: "libs/frontend/feature/admin/i18n/lib/src/catalogs.generated.ts",
    scopes: ["common", "admin"],
  },
  {
    id: "frontend-user",
    outputPath: "libs/frontend/feature/user/i18n/lib/src/catalogs.generated.ts",
    scopes: ["common", "user"],
  },
];

const generatedHeader = "// Generated by `pnpm nrb i18n catalogs`. Do not edit by hand.";
const identifierPattern = /^[A-Za-z_$][\w$]*$/u;

function pascalSegments(value: string): string {
  return value
    .split(/[^a-zA-Z0-9]+/u)
    .filter(Boolean)
    .map((segment) => `${segment.charAt(0).toUpperCase()}${segment.slice(1)}`)
    .join("");
}

function importIdentifier(locale: string, relativePath: string): string {
  const pascal = pascalSegments(`${locale}-${relativePath.replace(/\.json$/u, "")}`);
  return `${pascal.charAt(0).toLowerCase()}${pascal.slice(1)}Catalog`;
}

function catalogSpecifier(locale: string, relativePath: string): string {
  const separator = relativePath.indexOf("/");
  return `@app/i18n-${locale}-${relativePath.slice(0, separator)}/${relativePath.slice(separator + 1)}`;
}

function objectKey(value: string): string {
  return identifierPattern.test(value) ? value : `'${value}'`;
}

export function renderLocaleCatalogBinding(workspaceRoot: string, binding: LocaleCatalogBinding): string {
  const filesByLocale = supportedLocales.map((locale) => ({
    files: discoverLocaleCatalogFiles(workspaceRoot, locale, binding.scopes),
    locale,
  }));

  const imports = filesByLocale
    .flatMap(({ files, locale }) =>
      files.map(
        (relativePath) =>
          `import ${importIdentifier(locale, relativePath)} from '${catalogSpecifier(locale, relativePath)}';`,
      ),
    )
    .join("\n");

  const namespaces = filesByLocale[0]?.files ?? [];
  const catalogFileNames = namespaces.map((relativePath) => `  '${relativePath}',`).join("\n");

  const registry = filesByLocale
    .map(({ files, locale }) => {
      const entries = files
        .map((relativePath) => `    ['${relativePath}', ${importIdentifier(locale, relativePath)}],`)
        .join("\n");
      return `  ${objectKey(locale)}: [\n${entries}\n  ],`;
    })
    .join("\n");

  return [
    generatedHeader,
    imports,
    "import type { Locale, RuntimeLocaleCatalogFileEntry } from '@app/common-i18n-runtime';",
    "",
    "export const catalogFileNames = [",
    catalogFileNames,
    "] as const;",
    "",
    "export const localeCatalogFiles = {",
    registry,
    "} as const satisfies Record<Locale, readonly RuntimeLocaleCatalogFileEntry[]>;",
    "",
  ].join("\n");
}

/**
 * Formatting is normalized away before comparing. The generated modules live under `libs/`, where
 * Prettier owns the final layout (it collapses short arrays and unquotes identifier-shaped keys), so
 * an exact-text comparison would report drift for every file the formatter touched.
 */
function normalizeGeneratedSource(text: string): string {
  return text.replace(/\s+/gu, " ").trim();
}

export function checkLocaleCatalogBindings(workspaceRoot: string): string[] {
  return localeCatalogBindings.flatMap((binding) => {
    const target = resolve(workspaceRoot, binding.outputPath);
    if (!existsSync(target)) {
      return [`${binding.outputPath} is missing; run \`pnpm nrb i18n catalogs\`.`];
    }

    const expected = renderLocaleCatalogBinding(workspaceRoot, binding);
    return normalizeGeneratedSource(readFileSync(target, "utf8")) === normalizeGeneratedSource(expected)
      ? []
      : [`${binding.outputPath} is stale; run \`pnpm nrb i18n catalogs\`.`];
  });
}

export function writeLocaleCatalogBindings(workspaceRoot: string): string[] {
  return localeCatalogBindings.flatMap((binding) => {
    const target = resolve(workspaceRoot, binding.outputPath);
    const expected = renderLocaleCatalogBinding(workspaceRoot, binding);
    if (existsSync(target) && normalizeGeneratedSource(readFileSync(target, "utf8")) === normalizeGeneratedSource(expected)) {
      return [];
    }

    writeFileSync(target, expected);
    return [binding.outputPath];
  });
}
