import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import { defaultLocale } from "@app/common-i18n-runtime";

import { discoverLocaleCatalogFiles, localeDirectory } from "./catalog-sources.ts";

export const translationKeyModulePath = "libs/common/i18n/keys/lib/src/index.ts";

/**
 * The header carries no `=` and no quotes on purpose: the drift gate reads the union by slicing from
 * the first `=` and matching every quoted literal after it, so a chattier banner would be parsed as
 * translation keys.
 */
// One command regenerates every artifact derived from the locale axis, so both generated modules
// point the reader at that one command rather than at a per-artifact name nothing dispatches.
const generatedHeader = "// Generated by `pnpm nrb i18n catalogs`. Do not edit by hand.";

function byLocaleOrder(left: string, right: string): number {
  return left.localeCompare(right);
}

export function collectCatalogTranslationKeys(workspaceRoot: string, locale: string): string[] {
  const directory = localeDirectory(workspaceRoot, locale);
  const keys = new Set<string>();

  for (const relativePath of discoverLocaleCatalogFiles(workspaceRoot, locale)) {
    const catalog = JSON.parse(readFileSync(join(directory, relativePath), "utf8")) as unknown;
    if (catalog !== null && typeof catalog === "object" && !Array.isArray(catalog)) {
      for (const key of Object.keys(catalog)) {
        keys.add(key);
      }
    }
  }

  return [...keys].sort(byLocaleOrder);
}

export function renderTranslationKeyModule(keys: readonly string[]): string {
  const members = [...new Set(keys)].sort(byLocaleOrder);
  if (members.length === 0) {
    return `${generatedHeader}\nexport type TranslationKey = never;\n`;
  }

  const body = members.map((key) => `  | '${key}'`).join("\n");
  return `${generatedHeader}\nexport type TranslationKey =\n${body};\n`;
}

export function renderWorkspaceTranslationKeyModule(workspaceRoot: string, locale: string): string {
  return renderTranslationKeyModule(collectCatalogTranslationKeys(workspaceRoot, locale));
}

export function checkTranslationKeyModule(workspaceRoot: string, locale: string = defaultLocale): string[] {
  const target = resolve(workspaceRoot, translationKeyModulePath);
  const expected = renderWorkspaceTranslationKeyModule(workspaceRoot, locale);
  if (!existsSync(target)) {
    return [`${translationKeyModulePath} is missing; run \`pnpm nrb i18n keys\`.`];
  }

  return readFileSync(target, "utf8") === expected
    ? []
    : [`${translationKeyModulePath} is stale; run \`pnpm nrb i18n keys\`.`];
}

export function writeTranslationKeyModule(workspaceRoot: string, locale: string = defaultLocale): boolean {
  const target = resolve(workspaceRoot, translationKeyModulePath);
  const expected = renderWorkspaceTranslationKeyModule(workspaceRoot, locale);
  if (existsSync(target) && readFileSync(target, "utf8") === expected) {
    return false;
  }

  writeFileSync(target, expected);
  return true;
}
